force-app/main/default/objects/Linea_de_Proyecto__c/Linea_de_Proyecto__c.object-meta.xml
<CustomObject>
    <label>Línea de Proyecto</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Número de Línea de Proyecto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Proyecto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Práctica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gerencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Areas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Clase_PEP__c.field-meta.xml
<CustomField>
    <fullName>Clase_PEP__c</fullName>
    <formula>if(RecordType.DeveloperName==&apos;Llave_en_Mano&apos;,&apos;ZA&apos;,
if(text(Tipo_de_ingreso__c)==&apos;Por producción&apos;,&apos;ZM&apos;,
if(text(Tipo_de_ingreso__c)==&apos;Fijo mensual&apos;,&apos;ZB&apos;,
if(RecordType.DeveloperName==&apos;Guardias&apos;,&apos;ZN&apos;,
if(RecordType.DeveloperName==&apos;Hosting&apos;,&apos;ZK&apos;,
if(RecordType.DeveloperName==&apos;Licencias&apos;,&apos;ZG&apos;,
if(RecordType.DeveloperName==&apos;Licencias_Renovaci_n&apos;,&apos;ZG&apos;,
if(RecordType.DeveloperName==&apos;Licencias_Servicios&apos;,&apos;ZG&apos;,
if(RecordType.DeveloperName==&apos;TM&apos;,&apos;ZC&apos;,&apos;NONE&apos;


)))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clase PEP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Codigo_SAP_Ejecucion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP_Ejecucion__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP Ejecución</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Codigo_SAP_Preventa__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP_Preventa__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP Preventa</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Comercial_Intercompany__c.field-meta.xml
<CustomField>
    <fullName>Comercial_Intercompany__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Comercial de la filial.</description>
    <label>Comercial Intercompany</label>
    <referenceTo>User</referenceTo>
    <relationshipName>L_neas_de_Proyecto2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Coste_Bruto__c.field-meta.xml
<CustomField>
    <fullName>Coste_Bruto__c</fullName>
    <label>Total Coste Bruto</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Coste_estimado__c.field-meta.xml
<CustomField>
    <fullName>Coste_estimado__c</fullName>
    <label>Coste estimado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Ejecutado_en_cliente__c.field-meta.xml
<CustomField>
    <fullName>Ejecutado_en_cliente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ejecutado en cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Execution_SAP_Name__c.field-meta.xml
<CustomField>
    <fullName>Execution_SAP_Name__c</fullName>
    <label>Execution SAP Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Fabricantes__c.field-meta.xml
<CustomField>
    <fullName>Fabricantes__c</fullName>
    <label>Fabricantes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fabricantes_de_Licencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Fecha_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin__c</fullName>
    <label>Fecha Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Gerencia__c.field-meta.xml
<CustomField>
    <fullName>Gerencia__c</fullName>
    <label>Área</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Gerencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Importe_total_2__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_2__c</fullName>
    <description>Nuevo campo para poder indicar de forma manual el importe final</description>
    <label>Importe total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Jefe_de_Proyecto_de_Ejecucion__c.field-meta.xml
<CustomField>
    <fullName>Jefe_de_Proyecto_de_Ejecucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Jefe de Proyecto de Ejecución</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Jefe_de_Proyecto</value>
        </filterItems>
        <filterItems>
            <field>Contact.Activo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proyectos de Ejecución</relationshipLabel>
    <relationshipName>Lineas_de_JP_Ejecucion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Jefe_de_Proyecto_de_Preventa__c.field-meta.xml
<CustomField>
    <fullName>Jefe_de_Proyecto_de_Preventa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Operation user of the area involved</inlineHelpText>
    <label>Jefe de Proyecto de Preventa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Jefe de Proyecto</value>
        </filterItems>
        <filterItems>
            <field>Contact.Activo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proyectos de Preventa</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Jefe_Proyecto_Ejecucion_Adicional__c.field-meta.xml
<CustomField>
    <fullName>Jefe_Proyecto_Ejecucion_Adicional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Jefe Proyecto Ejecución Adicional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120N000000UzjjQAC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Líneas de Proyecto (Jefe Proyecto Ejecución Adicional)</relationshipLabel>
    <relationshipName>L_neas_de_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Linea_principal__c.field-meta.xml
<CustomField>
    <fullName>Linea_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si se trata o no del proyecto principal dentro de la oportunidad. Usado posteriormente para generar los PEPs en SAP.</description>
    <inlineHelpText>Shows if its the main opportunity proyect. Used after to generate PEP in SAP:</inlineHelpText>
    <label>Línea principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Listo_para_sincronizar__c.field-meta.xml
<CustomField>
    <fullName>Listo_para_sincronizar__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Manual check when all the fields required for the execution are completed correctly and are valid to send to SAP.</inlineHelpText>
    <label>Listo para sincronizar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Margen_bruto__c.field-meta.xml
<CustomField>
    <fullName>Margen_bruto__c</fullName>
    <label>Margen bruto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Margen_real__c.field-meta.xml
<CustomField>
    <fullName>Margen_real__c</fullName>
    <label>Margen real</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Margen_Real_Economico__c.field-meta.xml
<CustomField>
    <fullName>Margen_Real_Economico__c</fullName>
    <formula>if( Margen_real__c!=0 ,Margen_real__c,(1-(Coste_Bruto__c/Precio_Venta__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margen Real</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <formula>Text( Oportunidad__r.Mercado__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mercado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/NEW_Nombre_SAP__c.field-meta.xml
<CustomField>
    <fullName>NEW_Nombre_SAP__c</fullName>
    <label>Nombre SAP</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Nombre_SAP__c.field-meta.xml
<CustomField>
    <fullName>Nombre_SAP__c</fullName>
    <formula>if(  ISBLANK( NEW_Nombre_SAP__c )  , (LEFT(TRIM(&quot;ES-&quot;+  IF(ISNULL( Oportunidad__r.Account.Nombre_SAP__c ), LEFT(TRIM(Oportunidad__r.Account.Nombre_SAP__c  ) , 11), LEFT(TRIM(Oportunidad__r.Account.Name ) , 11))  +&quot;-&quot;  + &quot;-&quot; + Area_Corta__c +&quot;-&quot;+  RIGHT(Oportunidad__r.Codigo_de_oportunidad__c, 4)  +&quot;-&quot;  +  LEFT(Oportunidad__r.Name, 11)), 40)),NEW_Nombre_SAP__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre_SAP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oficina_tecnica__c.field-meta.xml
<CustomField>
    <fullName>Oficina_tecnica__c</fullName>
    <inlineHelpText>Technical office where the project line will be executed</inlineHelpText>
    <label>Oficina técnica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Oficina_t_cnica</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Líneas de Proyecto</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Org_Ventas__c.field-meta.xml
<CustomField>
    <fullName>Org_Ventas__c</fullName>
    <label>Org Ventas (Delivery Company)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Org_Ventas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Responsable_de_LDP__c.field-meta.xml
<CustomField>
    <fullName>Responsable_de_LDP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>antiguamente era el campo Responsable_de_la_oferta__c</description>
    <inlineHelpText>Operation user of the area involved</inlineHelpText>
    <label>Responsable de oferta(Operaciones)</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>El responsable de la oferta tiene que estar dada de alta como gerente en SAP.</errorMessage>
        <filterItems>
            <field>User.Gerente__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Sede__c.field-meta.xml
<CustomField>
    <fullName>Sede__c</fullName>
    <defaultValue>if( ISPICKVAL($User.Sede__c ,&apos;1210&apos;),&apos;1210&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1110&apos;),&apos;1110&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Perú&apos;),&apos;VASS Perú&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Colombia&apos;),&apos;VASS Colombia&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS México&apos;),&apos;VASS México&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Chile&apos;),&apos;VASS Chile&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS UK&apos;),&apos;VASS UK&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Benelux&apos;),&apos;VASS Benelux&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1800&apos;),&apos;1800&apos;,&apos;1000&apos;

)))))))))</defaultValue>
    <label>Sede (Delivery Company)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sede</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Sin_Controlling__c.field-meta.xml
<CustomField>
    <fullName>Sin_Controlling__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sin Controlling</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Tecnologia__c.field-meta.xml
<CustomField>
    <fullName>Tecnologia__c</fullName>
    <label>Competencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tecnologias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/UrlForm__c.field-meta.xml
<CustomField>
    <fullName>UrlForm__c</fullName>
    <formula>&apos;6&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UrlForm</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Venta_Extraordinaria__c.field-meta.xml
<CustomField>
    <fullName>Venta_Extraordinaria__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Venta Extraordinaria</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_SendEmailPepsEjecucion.cls
@isTest
private class Test_SendEmailPepsEjecucion {
    
    
    @TestSetup
    static void setupData(){
        //Crear Account
       Map<String, List<Object>> camposMapAcc = new Map<String, List<Object>>
       {
           
        'Name' => new List<String>{'AccTest1', 'AccTest2', 'AccTest3'},
        'Sede__c' => new List<String>{'2110', '2110', '2110'},
        'oficina_tecnica_SAP__c' => new List<String>{'1000', '1000', '1000'},
        'Mercado__c' => new List<String>{'Industria-Industria', 'Industria-Industria', 'Industria-Industria'},
        'ID_SAP__c' => new List<String>{'IDSAPTEST1','IDSAPTEST2', 'IDSAPTEST3'},
        'NIF_CIF__c' => new List<String>{'NIFCIF1','NIFCIF2', 'NIFCIF3'},
        'Razon_social__c' => new List<String>{'CUENTATEST1','CUENTATEST2', 'CUENTATEST3'},
        'BillingCountryCode' => new List<String>{'ES','ES', 'ES'},
        'SAP_Grupo_ID__c' => new List<String>{'IDSAPTEST1','IDSAPTEST2', 'IDSAPTEST3'},
        'CurrencyIsoCode' => new List<String>{'EUR','EUR', 'EUR'},
        'Validacion_NIF__c' => new List<Boolean>{true,true,true},
        'RecordTypeId' => new List<String>{Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.ACCOUNT_RECORDTYPE_EXTERNAL).RecordTypeId, 
                                           Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.ACCOUNT_RECORDTYPE_EXTERNAL).RecordTypeId, 
                                           Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.ACCOUNT_RECORDTYPE_INTERNAL).RecordTypeId}
   
       }; 
       
       List<Account> accs = TestUtil.rellenarSObject(Account.SObjectType, camposMapAcc);
       
       insert accs;

       Map<String, List<Object>> camposMapCont = new Map<String, List<Object>>
       {
           'LastName' 				=> new List<String>{'ContTest1','ContTest2','ContTest3'},
           'Codigo_de_empleado__c'	=> new List<String>{'12312378','12312379','12312370'},                
           'AccountId' => new List<String>{accs[0].Id,accs[1].Id,accs[2].Id},
           'Email' => new List<String>{'test.test1@test.com','test.test2@test.com','test.test3@test.com'},
           'RecordTypeId' => new List<String>{Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(Constants.CONTACT_RECORDTYPE_STANDAR).RecordTypeId,
                                                Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(Constants.CONTACT_RECORDTYPE_STANDAR).RecordTypeId,
                                                Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(Constants.CONTACT_RECORDTYPE_PROJECTMANAGER).RecordTypeId}
       }; 
        
       List<Contact> conts = TestUtil.rellenarSObject(Contact.SObjectType, camposMapCont);
       
       insert conts; 

       Map<String, List<Object>> camposMapOpp = new Map<String, List<Object>>
       {
           'Name' => new List<String>{'Opp101234','Opp1012345'},
           'ID_SAP__c'	=> new List<String>{'oprtunidadidsap1234','oprtunidadidsap12345'},    // una Opp con ID sap, ya en SAP, la otra para prueba enviar SAP            
           'CloseDate' => new List<Date>{date.newInstance(2024, 12, 12),date.newInstance(2023, 12, 12)},
           'RecordTypeId' => new List<String>{Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Constants.OPPORTUNITY_RECORDTYPE_PRESALE).RecordTypeId,
                                              Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Constants.OPPORTUNITY_RECORDTYPE_PRESALE).RecordTypeId},
           'StageName' => new List<String>{'Identificada','Identificada'},
           'Mercado__c' => new List<String>{'Industria-Retail','Industria-Retail'},
           'AccountId' => new List<String>{accs[0].Id,accs[0].Id},
           'Bid_Manager__c' => new List<String>{UserInfo.getUserId(),UserInfo.getUserId()},
           'Offering__c' => new List<String>{UserInfo.getUserId(),UserInfo.getUserId()}, 
           'Contacto_del_cliente__c' => new List<String>{conts[0].Id,conts[0].Id},
           'Fecha_de_propuesta_economica_tecnica__c' => new List<Date>{date.newInstance(2023, 11, 11),date.newInstance(2024, 11, 11)},
           'Fecha_de_propuesta_general__c' => new List<Date>{date.newInstance(2024, 11, 11),date.newInstance(2023, 11, 11)},
           'Codigo_de_oportunidad__c' => new List<String>{'VASS20180123456701','VASS20180123456702'}
       };
       System.debug('Campos mapa opp'+camposMapOpp);
       List<Opportunity> opps = TestUtil.rellenarSObject(Opportunity.SObjectType, camposMapOpp);

      
       insert opps;
       /*Map<String, List<Object>> camposMapLP = new Map<String, List<Object>>
       {
           'Oportunidad__c' => new List<String>{opps[0].Id},
           'Area__c' => new List<String>{'ES00T04006'},
           'Gerencia__c' => new List<String>{'Customer Centric'},
           'Responsable_de_LDP__c' => new List<String>{UserInfo.getUserId()},
           'Tecnologia__c' => new List<String>{'JAV', 'JAV'},
           'Listo_para_sincronizar__c' => new List<Boolean>{true, true},
           'Jefe_de_Proyecto_de_Preventa__c' => new List<String>{conts[0].Id},
           'Jefe_de_Proyecto_de_Ejecucion__c' => new List<String>{conts[0].Id},
           'Jefe_de_Proyecto_de_Ejecucion__c' => new List<String>{conts[0].Id},
           'Sede__c' => new List<String>{'1110'},
           'Oficina_tecnica__c' => new List<String>{'1000'},
           'Org_Ventas__c' => new List<String>{'1000'},
           'Coste_estimado__c' => new List<Decimal>{100},           
            'Margen_bruto__c' => new List<Decimal>{20}, 
            'Fecha_Inicio__c' => new List<Date>{date.newInstance(2022, 12, 00)}, 	
            'Fecha_Fin__c'=> new List<Date>{date.newInstance(2023, 12, 01)},
           'Responsable_de_LDP__c' => new List<String>{UserInfo.getUserId()},
           'Jefe_Proyecto_Ejecucion_Adicional__c' => new List<String>{conts[0].Id},
           'NEW_Nombre_SAP__c' => new List<String>{'Nuevo nombre sap 1'},
           'Linea_principal__c' => new List<Boolean>{true},
           'RecordTypeId' => new List<String>{Schema.SObjectType.Linea_de_proyecto__c.getRecordTypeInfosByDeveloperName().get(Constants.PROJECT_LINE_RECORDTYPE_TURNKEY).RecordTypeId}
       };
       
       System.debug('Campos mapa LP'+camposMapLP);
       List<Linea_de_Proyecto__c> lps = TestUtil.rellenarSObject(Linea_de_Proyecto__c.SObjectType, camposMapLP);
       
       insert lps;*/
       system.debug(conts[2]);
       List<Linea_de_Proyecto__c> lps = TestUtil.generaLineasLlaveManoTest(opps,conts);
       lps[0].Sede__c = '1100';
       lps[0].Linea_principal__c = true;
       update lps;

    }

    @isTest private static void enviarCorreoOKTest(){
        
        List<Linea_de_Proyecto__c> lps = [Select id,
        Nombre_SAP__c,
        Sede__c,
       Execution_SAP_Name__c,
        Oportunidad__r.Codigo_de_oportunidad__c 
        from Linea_de_Proyecto__c];

        SendEmailPepsEjecucion.enviarCorreo(lps[0]);
    }

    @isTest private static void enviarCorreoKOTest(){
        List<Linea_de_Proyecto__c> lps = [Select id,
        Nombre_SAP__c,
        Sede__c,
        Execution_SAP_Name__c,
        Oportunidad__r.Codigo_de_oportunidad__c 
        from Linea_de_Proyecto__c];

        SendEmailPepsEjecucion.enviarCorreo(lps[0],'Error');
    }

    @isTest private static void enviarCorreoAltaPEPTest(){
        List<Linea_de_Proyecto__c> lps = [Select id,
        Nombre_SAP__c,
        Sede__c,
        Execution_SAP_Name__c,
         urlForm__c,                                 
        Oportunidad__r.Codigo_de_oportunidad__c 
        from Linea_de_Proyecto__c];
        String []destinatarios = new String[]{'test.test23@test.com'};
        SendEmailPepsEjecucion.enviarCorreoAltaPEP(lps[0],destinatarios);
    }

    @isTest private static void generarPlantillaHTML(){
        List<Linea_de_Proyecto__c> lps = [Select id,
        Codigo_SAP_Preventa__c,
        Name,
        Nombre_SAP__c,
        urlForm__c,
        Area__c,
        Oficina_tecnica__c,
        Fecha_Fin__c, 
        Fecha_Inicio__c,
        Gerencia__c,
        RecordType.Name,
        RecordTypeId,
        Oportunidad__r.Owner.Email,
        Jefe_de_Proyecto_de_Preventa__r.Codigo_de_empleado__c,
        Jefe_Proyecto_Ejecucion_Adicional__r.Codigo_de_empleado__c,
        Margen_real__c,
        Importe_total_2__c,
        Responsable_de_LDP__r.EmployeeNumber,
        Responsable_de_LDP__r.Name,
        Tecnologia__c,
        Oportunidad__r.Proyecto_Padre__c,
        Oportunidad__r.Oportunidad_Relacionada__r.Proyecto_Padre__c,
        Oportunidad__r.Proyecto_extraordinario__c,
        Oportunidad__r.Codigo_de_oportunidad__c,
        Oportunidad__r.CreatedDate,
        Oportunidad__r.Account.ID_SAP__c,
        Oportunidad__r.Margen_bruto__c,
        Oportunidad__r.Owner.EmployeeNumber,
        Jefe_de_Proyecto_de_Ejecucion__r.Codigo_de_empleado__c,  
        Oportunidad__r.Offering__r.EmployeeNumber,
        Oportunidad__r.Offering__r.Profile.Id,
        Comercial_Intercompany__r.EmployeeNumber,
        CreatedById,
        Fabricantes__c,
        Sede__c,
        Coste_Bruto__c,
        Execution_SAP_Name__c,
        Margen_Real_Economico__c,
        Oportunidad__r.Sede_Venta__r.Oficina_tecnica_SAP__c,
        Oportunidad__r.mercado__c,
        Org_Ventas__c,
        Clase_PEP__c,
        Codigo_SAP_Ejecucion__c,
        CurrencyIsoCode,
        Venta_Extraordinaria__c,
        oportunidad__r.Proyecto_estrategico__c,
        Sin_Controlling__c,
        Ejecutado_en_cliente__c,
        Direccion_cliente__c,
        Clave_Periodificacion__c,
        Agile__c,
        Cambio_Alcance__c,
        Jefe_de_Proyecto_de_Ejecucion__r.Email,
        Sin_Contrato__c,
        ToLabel(Inducido__c),
        CreatedBy.EmployeeNumber,
        Jefe_Proyecto_Ejecucion_Adicional__r.name,
        Jefe_de_Proyecto_de_Ejecucion__r.Name,
        Oportunidad__r.Owner.Name,
        Oportunidad__r.Account.Name,
        Coste_real__c,
        Importe_a_elevar__c
        from Linea_de_Proyecto__c];
        SendEmailPepsEjecucion.generarPlantillaHTML(lps[0]);
    }

    @isTest private static void generarPlantillaOKTest(){
        List<Linea_de_Proyecto__c> lps = [Select id,
        Nombre_SAP__c,
        Sede__c,
        Execution_SAP_Name__c,
        Oportunidad__r.Codigo_de_oportunidad__c 
        from Linea_de_Proyecto__c];
        SendEmailPepsEjecucion.generarPlantillaOK(lps[0]);
    }

    @isTest private static void generarPlantillaKOTest(){
        List<Linea_de_Proyecto__c> lps = [Select id,
        Nombre_SAP__c,
        Sede__c,
        Execution_SAP_Name__c,
        Oportunidad__r.Codigo_de_oportunidad__c 
        from Linea_de_Proyecto__c];
        SendEmailPepsEjecucion.generarPlantillaKO(lps[0],'Error al mandar el correo.');
    }
}