force-app/main/default/objects/Linea_de_Proyecto__c/Linea_de_Proyecto__c.object-meta.xml
<CustomObject>
    <label>Línea de Proyecto</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Número de Línea de Proyecto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Proyecto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Práctica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gerencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Areas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Clave_de_Periodificacion__c.field-meta.xml
<CustomField>
    <fullName>Clave_de_Periodificacion__c</fullName>
    <label>Clave de Periodificación</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Codigo_SAP_Ejecucion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP_Ejecucion__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP Ejecución</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Fecha_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin__c</fullName>
    <label>Fecha Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Gerencia__c.field-meta.xml
<CustomField>
    <fullName>Gerencia__c</fullName>
    <label>Área</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Gerencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Importe_total_2__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_2__c</fullName>
    <description>Nuevo campo para poder indicar de forma manual el importe final</description>
    <label>Importe total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Jefe_de_Proyecto_de_Ejecucion__c.field-meta.xml
<CustomField>
    <fullName>Jefe_de_Proyecto_de_Ejecucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Jefe de Proyecto de Ejecución</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Jefe_de_Proyecto</value>
        </filterItems>
        <filterItems>
            <field>Contact.Activo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proyectos de Ejecución</relationshipLabel>
    <relationshipName>Lineas_de_JP_Ejecucion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Jefe_de_Proyecto_de_Preventa__c.field-meta.xml
<CustomField>
    <fullName>Jefe_de_Proyecto_de_Preventa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Operation user of the area involved</inlineHelpText>
    <label>Jefe de Proyecto de Preventa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Jefe de Proyecto</value>
        </filterItems>
        <filterItems>
            <field>Contact.Activo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proyectos de Preventa</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Margen_real__c.field-meta.xml
<CustomField>
    <fullName>Margen_real__c</fullName>
    <label>Margen real</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <formula>Text( Oportunidad__r.Mercado__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mercado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Responsable_de_LDP__c.field-meta.xml
<CustomField>
    <fullName>Responsable_de_LDP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>antiguamente era el campo Responsable_de_la_oferta__c</description>
    <inlineHelpText>Operation user of the area involved</inlineHelpText>
    <label>Responsable de oferta(Operaciones)</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>El responsable de la oferta tiene que estar dada de alta como gerente en SAP.</errorMessage>
        <filterItems>
            <field>User.Gerente__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Tecnologia__c.field-meta.xml
<CustomField>
    <fullName>Tecnologia__c</fullName>
    <label>Competencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tecnologias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/recordTypes/AM.recordType-meta.xml
<RecordType>
    <fullName>AM</fullName>
    <active>true</active>
    <label>AM</label>
</RecordType>

force-app/main/default/objects/Linea_de_Proyecto__c/recordTypes/Licencias.recordType-meta.xml
<RecordType>
    <fullName>Licencias</fullName>
    <active>true</active>
    <label>Licencias</label>
</RecordType>

force-app/main/default/objects/Linea_de_Proyecto__c/recordTypes/Licencias_Renovaci_n.recordType-meta.xml
<RecordType>
    <fullName>Licencias_Renovaci_n</fullName>
    <active>true</active>
    <label>Licencias - Renovación</label>
</RecordType>

force-app/main/default/objects/Linea_de_Proyecto__c/recordTypes/Licencias_Servicios.recordType-meta.xml
<RecordType>
    <fullName>Licencias_Servicios</fullName>
    <active>true</active>
    <label>Licencias - Servicios</label>
</RecordType>

force-app/main/default/objects/Linea_de_Proyecto__c/recordTypes/Llave_en_Mano.recordType-meta.xml
<RecordType>
    <fullName>Llave_en_Mano</fullName>
    <active>true</active>
    <label>Llave en Mano</label>
</RecordType>

force-app/main/default/objects/Linea_de_Proyecto__c/recordTypes/TM.recordType-meta.xml
<RecordType>
    <fullName>TM</fullName>
    <active>true</active>
    <label>T&amp;M</label>
</RecordType>

force-app/main/default/classes/Constants.cls
public class Constants 
{

    public static final string CAMPAIGN_RECORDTYPE_INTERNAL = 'Campana_interna';
    public static final string CAMPAIGN_STATE_PLANIFIED = 'Planificada';
	public static final string CAMPAIGN_STATE_ACTIVE = 'Activa';
    public static final string CAMPAIGN_STATE_ENDED = 'Finalizada';
    
    public static final string NAMED_CREDENTIALS_SAP = 'Current_Org';

    public static final string SAP_ACCOUNTS_PATH = '/services/apexrest/TestWS';
    /*LAS 3 SIGUIENTES VARIABLES SIRVEN PARA ESPECIFICAR EL ENDPOINT DE UNA LLAMADA REST*/
    public static final string SAP_LPS_PREVENTA_PATH = '';  //POR DEFINR
    public static final string SAP_LPS_EJECUCION_PATH = ''; //POR DEFINIR
    public static final string SAP_OPPORTUNITIES_PATH = ''; //POR DEFINIR

    ///////////////////////////OPPORTUNITY STAGE DEVELOPERNAMES 
    public static final string OPPORTUNITY_STAGE_IDENTIFIED = 'Identificada';
    public static final string OPPORTUNITY_STAGE_PRESALE = 'Preventa';
    public static final string OPPORTUNITY_STAGE_SUBMITTED = 'Entregada';
    public static final string OPPORTUNITY_STAGE_DISPLAYED = 'Presentada';
    public static final string OPPORTUNITY_STAGE_WON = 'Ganada';

    ///////////////////////////OPPORTUNITY RECORDTYPE DEVELOPERNAMES 
    public static final string OPPORTUNITY_RECORDTYPE_PRESALE = 'Preventa';
    public static final string OPPORTUNITY_RECORDTYPE_CONCEPTUALIZATION = 'Conceptualizacion';
    public static final string OPPORTUNITY_RECORDTYPE_TM = 'TM';
    public static final string OPPORTUNITY_RECORDTYPE_RENOVACION = 'Renovacion';

	public static final string TASK_RECORDTYPE_ACTIONPLAN = 'Action Plan';
    //AnaliticaRecordTypes
    public static final string TASK_RECORDTYPE_DEVCACTIONPLAN = 'Action_Plan';
    
    public static final string ANALITIC_FORECAST_LINEAS = 'ForecastDeLinea';
    public static final string ANALITIC_FORECAST_OPORTUNIDADES = 'ForecastDeOportunidades';

    public static final string ANALITIC_FORECAST_LINEAS_Rafa = 'ForecastImporteTotal_Presupuesto';
    public static final string ANALITIC_FORECAST_OPORTUNIDADES_Rafa = 'ForecastImporteXprob_Presupuesto';
  


    public static final string ACCOUNT_RECORDTYPE_INTERNAL = 'Cuenta_interna';
    public static final string ACCOUNT_RECORDTYPE_EXTERNAL = 'Cuenta_externa';
    public static final string ACCOUNT_RECORDTYPE_GROUP = 'Grupo';

    public static final string PROJECT_LINE_RECORDTYPE_AM = 'AM';
    public static final string PROJECT_LINE_RECORDTYPE_LICENSES = 'Licencias';
    public static final string PROJECT_LINE_RECORDTYPE_TURNKEY = 'Llave_en_Mano';
    public static final string PROJECT_LINE_RECORDTYPE_RENOVE = 'Licencias_Renovaci_n';
    public static final string PROJECT_LINE_RECORDTYPE_SERVICIOS = 'Licencias_Servicios';



    public static final string CONTACT_RECORDTYPE_PROJECTMANAGER = 'Jefe_de_Proyecto';
    public static final string CONTACT_RECORDTYPE_STANDAR = 'Ordinario';


    public static final string DEFAULT_TEAM_MEMBER_ROLE_OPPORTUNITY_TEAM = 'Equipo_generado';
    public static final string DEFAULT_ACCESS_LEVEL_OPPORTUNITY_TEAM = 'Edit';
    public static final string DEFAULT_ACCESS_LEVEL_ACC_WHEN_SHARING_OPPTY = 'Read';
    public static final string DEFAULT_ACCESS_LEVEL_OPPS_WHEN_SHARING_OPPTY = 'None';
    public static final string DEFAULT_OPPORTUNITY_OFFICE_ACCOUNT_NAME = 'VASS Madrid';

    /*LA SIGUIENTE VARIABLE ESTABLECE LOS CAMPOS CUYO VALOR SE DEBE COMPROBAR QUE HA CAMBIADO (AL MENOS UNO) PARA ENVIAR UNA CUENTA A SINCRONIZAR TRAS SU ACTUALIZACION*/
    public static final List<string> CAMPOS_A_COMPROBAR_ACCOUNT = new List<String>
    {   
                                                                                        'Name', 
                                                                                        'Razon_Social__c', 
                                                                                        'NIF_CIF__c', 
                                                                                        'BillingAddress', 
                                                                                        'BillingStreet', 
                                                                                        'BillingCity', 
                                                                                        'BillingCountryCode', 
                                                                                        'BillingPostalCode', 
                                                                                        'Phone', 
                                                                                        'Fax', 
                                                                                        'Mercado__c', 
                                                                                        'Sectores__c'
    };

    //---------Linea_de_Proyecto__c----------------CAMPOS--------------------
    //Lista de campos necesarios para invocar el WS de de actualización de PEP
    public static final List<String> CAMPOS_COMPROBAR_LINEA_PREVENTA = new List<String>
    {
                                                                                        'Name',
                                                                                        'Area__c',
                                                                                        'Fecha_Fin__c',
                                                                                        'Fecha_Inicio__c',
                                                                                        'Gerencia__c',
                                                                                        'Jefe_de_Proyecto_de_Preventa__c',
                                                                                        'Margen_real__c',
                                                                                        'Importe_total_2__c',
                                                                                        'Responsable_de_LDP__c',
                                                                                        'Tecnologia__c'
    }; 

    public static final List<String> CAMPOS_COMPROBAR_LINEA_EJECUCION = new List<String>
    {
                                                                                        'Name',
                                                                                        'Codigo_SAP_Ejecucion__c',
                                                                                        'Area__c',
                                                                                        'Clave_de_Periodificacion__c',
                                                                                        'Fecha_Fin__c',
                                                                                        'Fecha_Inicio__c',
                                                                                        'Gerencia__c',
                                                                                        'Jefe_de_Proyecto_de_Ejecucion__c',
                                                                                        'Margen_real__c',
                                                                                        'Importe_total_2__c',
                                                                                        'Responsable_de_LDP__c',
                                                                                        'Tecnologia__c'
    };

    public static final List<String> ESTADOS_OPP_RELACIONADA_PREVENTA = new List<String>{'Preventa','Presentada','Entregada'};



    ////////////////////////////////////////////////////SECTORES////////////////////////////////////////////////////////////////////
    //Mapeo de códigos de sectores en SAP VS nombres en Salesforce
    public static final Map<String,String> SECTORESSAP = new Map<String,String>
    {
        'Estruct.-Estructura'       => '00',
        'A.Pub-Admin. Pública'      => '10',
        'Banca-Banca'               => '20',
        'Telco-Telco'               => '30',
        'Telco-Media'               => '40',
        'Industria-Industria'       => '60',
        'Seguros-Seguros'           => '70',
        'Environment'               => '80',
        'Energía'                   => '90'
    };

    ////////////////////////////////////////////////////MERCADOS////////////////////////////////////////////////////////////////////
    //Mapeo de códigos de mercados en SAP VS nombres de sectores en Salesforce   
    public static final Map<String,String> MERCADOSSAP = new Map<String,String>
    {
        'Estruct.-Estructura'       => '00',     
        'A.Pub-Admin. Pública'      => '10',          
        'Banca-Banca'               => '20',      
        'Telco-Telco'               => '30',              
        'TTelco-Media'              => '30',              
        'Industria-Industria'       => '40', 
        'Seguros Global'            => '50',          
        'Environment'               => '60',              
        'Energía'                   => '60'              
    };


public static final List<String> SEDE_VENTA_SINCRO_SAP = new List<String>{'VASS Madrid2'};

    public static final List<String> SEDE_SINCRO_SAP = new List<String>{'1210','1000','	1110'};
    
    public static final List<String> REGION_CUENTA_SINCRO_SAP = new List<String>{'Madrid','Barcelona','Sedes España'};

    public static final List<String> DIVISAS_CRM = new List<String>{'AUD', 'CAD', 'CHF', 'CLP', 'COP', 'DKK', 'EUR', 'GBP', 'MKD', 'MXN', 'MYR', 'NOK', 'PEN', 'RON', 'SEK', 'SGD', 'USD'};
}