force-app/main/default/objects/Linea_de_Proyecto__c/Linea_de_Proyecto__c.object-meta.xml
<CustomObject>
    <label>Línea de Proyecto</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Número de Línea de Proyecto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Proyecto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Gerencia__c.field-meta.xml
<CustomField>
    <fullName>Gerencia__c</fullName>
    <label>Área</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Gerencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Líneas de Proyecto</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Sede__c.field-meta.xml
<CustomField>
    <fullName>Sede__c</fullName>
    <defaultValue>if( ISPICKVAL($User.Sede__c ,&apos;1210&apos;),&apos;1210&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1110&apos;),&apos;1110&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Perú&apos;),&apos;VASS Perú&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Colombia&apos;),&apos;VASS Colombia&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS México&apos;),&apos;VASS México&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Chile&apos;),&apos;VASS Chile&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS UK&apos;),&apos;VASS UK&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Benelux&apos;),&apos;VASS Benelux&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1800&apos;),&apos;1800&apos;,&apos;1000&apos;

)))))))))</defaultValue>
    <label>Sede (Delivery Company)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sede</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/OppTeamBatch.cls
/**
 * @author Adrián Bernardo Monedero
 * Batch to insert Opportunity Team Members automatically
 */
global class OppTeamBatch implements Database.Batchable<sObject>{
    global string userId;
    global string query;
    global string clan;
    global string sede;
    global boolean hasLP;
    global string technicalOffice;

    global OppTeamBatch(String userId,String clan,String sede,boolean hasLP){
        this.userId = userId;
        this.clan = clan;
        this.sede = sede;
        this.hasLP = hasLP;
        this.query = createQuery(this.clan,this.sede,this.hasLP);
    } 

    global Database.QueryLocator start(Database.BatchableContext BC){
          System.debug('QUERY LANZADA ---->'+query);
          return Database.getQueryLocator(query);
    }
    
    
    global void execute(Database.BatchableContext BC,List<sObject> scope) {
        
        try{
            list<OpportunityTeamMember> oppTeamMembers = new list<OpportunityTeamMember>();

            if(scope.get(0).getSObjectType() == Opportunity.getSObjectType()){
                for(Opportunity opp : (List<Opportunity>) scope){
                    OpportunityTeamMember teamMember = new OpportunityTeamMember();
                    teamMember.OpportunityId = opp.id;
                    teamMember.OpportunityAccessLevel = 'Edit';
                    teamMember.TeamMemberRole = 'Equipo_generado';
                    teamMember.userID = userID;
                    oppTeamMembers.add(teamMember);
                }
            }else{
                for(Linea_de_Proyecto__c PL : (List<Linea_de_Proyecto__c>) scope){
                    OpportunityTeamMember teamMember = new OpportunityTeamMember();
                    teamMember.OpportunityId = pl.Oportunidad__c;
                    teamMember.OpportunityAccessLevel = 'Edit';
                    teamMember.TeamMemberRole = 'Equipo_generado';
                    teamMember.userID = userID;
                    oppTeamMembers.add(teamMember);
                }
            }
       
       

        if(!oppTeamMembers.isEmpty()){
           List<Database.SaveResult> sresultList = Database.insert(oppTeamMembers,false);
           if(!sresultList.isEmpty()){
            for(Database.SaveResult sr : sresultList){
                if(!sr.isSuccess()){
                    system.debug('Error al insertar el registro '+sr.getErrors() + ' / '+sr.getId());
                }
            }
        }
        }

    } catch(Exception ex){
        system.debug(ex.getCause()+'//'+ex.getMessage());
    }

        
    }
    
      global void finish(Database.BatchableContext BC) {
        System.debug(LoggingLevel.WARN,'Batch Job terminado.');
   }

   /**
    * @description creates a dynamic query depending on the parameters the batch received.
    * @author Adrián Bernardo Monedero
    * @date 26/03/2023
    * @return retuns the query ,.................................l´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´ws-dfffffffto use by the batch.
    */
   public String createQuery(String clan,String sede,Boolean hasLP){
        String queryADevolver = hasLP ? 'select Oportunidad__c from Linea_de_Proyecto__c WHERE Oportunidad__c != null AND Oportunidad__r.StageName IN (\'Pendiente Aprobacion\',\'Presentada\',\'Entregada\',\'Preventa\',\'Solicitada\',\'Identificada\') ' : 'select id from Opportunity WHERE StageName IN (\'Pendiente Aprobacion\',\'Presentada\',\'Entregada\',\'Preventa\',\'Solicitada\',\'Identificada\') ';
        if(!String.isBlank(clan) && clan != null){
            queryADevolver += hasLP ? ' AND Gerencia__c =\''+clan+'\'' : ' AND Clan_Principal__c =\''+clan+'\'';
        }
        if(!String.isBlank(sede) && sede != null){
            queryADevolver += hasLP ? ' AND Oportunidad__r.Owner.Sede__c =\''+sede+'\'' : ' AND Owner.Sede__c =\''+sede+'\'';
        }

        return queryADevolver;
   }

}