force-app/main/default/objects/Linea_de_Proyecto__c/Linea_de_Proyecto__c.object-meta.xml
<CustomObject>
    <label>Línea de Proyecto</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Número de Línea de Proyecto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Proyecto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Práctica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gerencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Areas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Direccion_cliente__c.field-meta.xml
<CustomField>
    <fullName>Direccion_cliente__c</fullName>
    <label>Direccion cliente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Duracion_lineas_por_meses__c.field-meta.xml
<CustomField>
    <fullName>Duracion_lineas_por_meses__c</fullName>
    <formula>IF( 
(Fecha_Fin__c - Fecha_Inicio__c) / 365 * 12 &lt; 1, 1, (Fecha_Fin__c - Fecha_Inicio__c ) / 365 * 12)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duración lineas por meses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Ejecutado_en_cliente__c.field-meta.xml
<CustomField>
    <fullName>Ejecutado_en_cliente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ejecutado en cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/English__c.field-meta.xml
<CustomField>
    <fullName>English__c</fullName>
    <label>English</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Proficiency</fullName>
            </value>
            <value>
                <fullName>Elementary Proficiency</fullName>
            </value>
            <value>
                <fullName>Limited Working Proficiency</fullName>
            </value>
            <value>
                <fullName>Professional Working Proficiency</fullName>
            </value>
            <value>
                <fullName>Full Professional Proficiency</fullName>
            </value>
            <value>
                <fullName>Native or Bilingual Proficiency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Estimated_date_of_incorporation__c.field-meta.xml
<CustomField>
    <fullName>Estimated_date_of_incorporation__c</fullName>
    <label>Estimated date of incorporation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Gerencia__c.field-meta.xml
<CustomField>
    <fullName>Gerencia__c</fullName>
    <label>Área</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Gerencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Importe_total__c.field-meta.xml
<CustomField>
    <fullName>Importe_total__c</fullName>
    <formula>(Coste_estimado__c / (1 - Margen_bruto__c)) + Importe_de_licencias__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Importe total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Is_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Is_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Renewal?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Jefe_de_Proyecto_de_Ejecucion__c.field-meta.xml
<CustomField>
    <fullName>Jefe_de_Proyecto_de_Ejecucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Jefe de Proyecto de Ejecución</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Jefe_de_Proyecto</value>
        </filterItems>
        <filterItems>
            <field>Contact.Activo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proyectos de Ejecución</relationshipLabel>
    <relationshipName>Lineas_de_JP_Ejecucion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Margen_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Margen_de_venta__c</fullName>
    <description>Cálculo del margen en base al precio y al coste</description>
    <formula>if( Importe_de_licencias__c &gt;0,Margen_de_licencias__c,((Importe_total_2__c - Coste_estimado__c) / Importe_total_2__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margen de venta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <formula>Text( Oportunidad__r.Mercado__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mercado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/n_vacantes__c.field-meta.xml
<CustomField>
    <fullName>n_vacantes__c</fullName>
    <label>No. of vacancies</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Líneas de Proyecto</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Org_Ventas__c.field-meta.xml
<CustomField>
    <fullName>Org_Ventas__c</fullName>
    <label>Org Ventas (Delivery Company)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Org_Ventas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Profile_Description__c.field-meta.xml
<CustomField>
    <fullName>Profile_Description__c</fullName>
    <label>Profile Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Sede__c.field-meta.xml
<CustomField>
    <fullName>Sede__c</fullName>
    <defaultValue>if( ISPICKVAL($User.Sede__c ,&apos;1210&apos;),&apos;1210&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1110&apos;),&apos;1110&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Perú&apos;),&apos;VASS Perú&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Colombia&apos;),&apos;VASS Colombia&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS México&apos;),&apos;VASS México&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Chile&apos;),&apos;VASS Chile&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS UK&apos;),&apos;VASS UK&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Benelux&apos;),&apos;VASS Benelux&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1800&apos;),&apos;1800&apos;,&apos;1000&apos;

)))))))))</defaultValue>
    <label>Sede (Delivery Company)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sede</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Working_Model__c.field-meta.xml
<CustomField>
    <fullName>Working_Model__c</fullName>
    <label>Working Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Smartworking</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Full Remote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CornestoneWS.cls
@RestResource(urlMapping='/GetCSODdata')
global with sharing class CornestoneWS {
    
    @HttpGet
    global static void getConerData() {
        // Obtener los parámetros de fecha de la URL
        String startDate = RestContext.request.params.get('startDate');
        String endDate = RestContext.request.params.get('endDate');
        
        // Construir el query de SOQL
        String query = 'SELECT id, Oportunidad__r.Name ,Sede__c,Org_Ventas__c, CurrencyIsoCode,createddate, RecordType.Name, rate__c,lastmodifieddate, Ejecutado_en_cliente__c, ' +
                       'Direccion_cliente__c, Duracion_lineas_por_meses__c, Oportunidad__r.Mercado__c, Oportunidad__r.Account.Name, ' +
                       'ToLabel(Gerencia__c), Area__c, English__c, Profile_Description__c, Oportunidad__r.Owner.Name,working_model__c, ' +
                       'Jefe_de_Proyecto_de_Ejecucion__r.Name, n_vacantes__c, Estimated_date_of_incorporation__c, ' +
                       'Oportunidad__r.Codigo_de_oportunidad__c,Oportunidad__r.Probability,Margen_de_venta__c,Importe_total__c FROM Linea_de_Proyecto__c';
        
        // Verificar si se han proporcionado las fechas de inicio y fin
        if (startDate != null && endDate != null) {
            try {
                // Validar el formato de las fechas recibidas
                DateTime startDateTime = DateTime.valueOfGmt(startDate);
                DateTime endDateTime = DateTime.valueOfGmt(endDate);
                
                // Agregar cláusula WHERE para filtrar por la fecha de modificación
                query += ' where (LastModifiedDate >= :startDateTime AND LastModifiedDate <= :endDateTime) and Estimated_date_of_incorporation__c!=null and Is_Renewal__c=False   ORDER BY LastModifiedDate DESC ';
            } catch (Exception e) {
                // Manejo de error para fechas no válidas
                RestContext.response.statusCode = 400;
                RestContext.response.responseBody = Blob.valueOf('Invalid date format. Please provide dates in the format "YYYY-MM-DDTHH:MM:SSZ".');
                return;
            }
        }else {
             query += ' where Estimated_date_of_incorporation__c!=null and Is_Renewal__c=False    ORDER BY LastModifiedDate DESC ';
        }
        
        // Completar la consulta con orden y límite
       
        
        // Ejecutar la consulta
        List<Linea_de_Proyecto__c> projectLines = Database.query(query);
        
        // Crear una lista de objetos de salida
        List<Map<String, Object>> resultList = new List<Map<String, Object>>();
        String serviceLine;
        // Mapear los resultados a la estructura JSON solicitada
        for (Linea_de_Proyecto__c line : projectLines) {
            Map<String, Object> projectData = new Map<String, Object>();
            
            // Mapeo de campos específicos
            projectData.put('Id', line.id);
            projectData.put('Display_job_title', line.Oportunidad__r.Name);
            projectData.put('Company', line.Sede__c);
            projectData.put('Location', line.Org_Ventas__c);
            projectData.put('SalesforceID', line.Oportunidad__r.Codigo_de_oportunidad__c);
            projectData.put('Currency', line.CurrencyIsoCode);
            projectData.put('Range', line.rate__c);
            projectData.put('Type_of_Project', line.RecordType.Name);
            projectData.put('Working_Model', line.working_model__c);
            projectData.put('Address_of_Working Place', line.Direccion_cliente__c);
            projectData.put('Duration_of_contract', line.Duracion_lineas_por_meses__c);
            projectData.put('Business_Vertical', line.Oportunidad__r.Mercado__c);
            projectData.put('Customer', line.Oportunidad__r.Account.Name);
            if (line.Gerencia__c == 'Integration & Processes') {
                serviceLine = 'AUTOMATION & INTEGRATION';
            } else if (line.Gerencia__c == 'Infrastructure & SecDevOps') {
                serviceLine = 'CLOUD & SECDEVOPS';
            } else {
                serviceLine = line.Gerencia__c;
            }
            projectData.put('Service_Line', serviceLine);
            projectData.put('Practice', line.Area__c);
            projectData.put('English', line.English__c);
            projectData.put('Description', line.Profile_Description__c);
            projectData.put('Hiring_manager', line.Oportunidad__r.Owner.Name);
            projectData.put('Reviewer', line.Jefe_de_Proyecto_de_Ejecucion__r.Name);
            projectData.put('Openings', line.n_vacantes__c ?? 1);
            projectData.put('Target_hire_date', line.Estimated_date_of_incorporation__c);
            projectData.put('CreatedDate', line.createddate);
            projectData.put('Margin', line.Margen_de_venta__c);
            projectData.put('Probability', line.Oportunidad__r.Probability);
            projectData.put('Amount', line.Importe_total__c);
            projectData.put('ModifiedDate', line.lastmodifieddate);
            // Agregar el mapa a la lista de resultados
            resultList.add(projectData);
        }
        
        // Crear la estructura final de la respuesta
        Map<String, Object> finalResult = new Map<String, Object>();
        finalResult.put('records', resultList);
        finalResult.put('totalSize', projectLines.size()); // Número total de registros
        finalResult.put('done', true); // Estado de la operación
        
        // Devolver el resultado como JSON
        RestContext.response.addHeader('Content-Type', 'application/json');
        RestContext.response.responseBody = Blob.valueOf(JSON.serialize(finalResult));
        RestContext.response.statusCode = 200;
    }
}