force-app/main/default/objects/Linea_de_Proyecto__c/Linea_de_Proyecto__c.object-meta.xml
<CustomObject>
    <label>Línea de Proyecto</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Número de Línea de Proyecto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Proyecto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Práctica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gerencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Areas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Clave_de_Periodificacion__c.field-meta.xml
<CustomField>
    <fullName>Clave_de_Periodificacion__c</fullName>
    <label>Clave de Periodificación</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Codigo_SAP_Ejecucion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP_Ejecucion__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP Ejecución</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Codigo_SAP_Preventa__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP_Preventa__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP Preventa</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Fecha_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin__c</fullName>
    <label>Fecha Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Gerencia__c.field-meta.xml
<CustomField>
    <fullName>Gerencia__c</fullName>
    <label>Área</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Gerencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Importe_total_2__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_2__c</fullName>
    <description>Nuevo campo para poder indicar de forma manual el importe final</description>
    <label>Importe total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Jefe_de_Proyecto_de_Preventa__c.field-meta.xml
<CustomField>
    <fullName>Jefe_de_Proyecto_de_Preventa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Operation user of the area involved</inlineHelpText>
    <label>Jefe de Proyecto de Preventa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Jefe de Proyecto</value>
        </filterItems>
        <filterItems>
            <field>Contact.Activo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proyectos de Preventa</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Linea_principal__c.field-meta.xml
<CustomField>
    <fullName>Linea_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si se trata o no del proyecto principal dentro de la oportunidad. Usado posteriormente para generar los PEPs en SAP.</description>
    <inlineHelpText>Shows if its the main opportunity proyect. Used after to generate PEP in SAP:</inlineHelpText>
    <label>Línea principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Listo_para_sincronizar__c.field-meta.xml
<CustomField>
    <fullName>Listo_para_sincronizar__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Manual check when all the fields required for the execution are completed correctly and are valid to send to SAP.</inlineHelpText>
    <label>Listo para sincronizar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Margen_real__c.field-meta.xml
<CustomField>
    <fullName>Margen_real__c</fullName>
    <label>Margen real</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/No_aplica_para_ejecucion__c.field-meta.xml
<CustomField>
    <fullName>No_aplica_para_ejecucion__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this project line does not count towards the pipeline, it will not be synchronized with SAP</inlineHelpText>
    <label>No aplica para ejecución</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Nombre_SAP__c.field-meta.xml
<CustomField>
    <fullName>Nombre_SAP__c</fullName>
    <formula>if(  ISBLANK( NEW_Nombre_SAP__c )  , (LEFT(TRIM(&quot;ES-&quot;+  IF(ISNULL( Oportunidad__r.Account.Nombre_SAP__c ), LEFT(TRIM(Oportunidad__r.Account.Nombre_SAP__c  ) , 11), LEFT(TRIM(Oportunidad__r.Account.Name ) , 11))  +&quot;-&quot;  + &quot;-&quot; + Area_Corta__c +&quot;-&quot;+  RIGHT(Oportunidad__r.Codigo_de_oportunidad__c, 4)  +&quot;-&quot;  +  LEFT(Oportunidad__r.Name, 11)), 40)),NEW_Nombre_SAP__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre_SAP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oficina_tecnica__c.field-meta.xml
<CustomField>
    <fullName>Oficina_tecnica__c</fullName>
    <inlineHelpText>Technical office where the project line will be executed</inlineHelpText>
    <label>Oficina técnica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Oficina_t_cnica</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Líneas de Proyecto</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Responsable_de_LDP__c.field-meta.xml
<CustomField>
    <fullName>Responsable_de_LDP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>antiguamente era el campo Responsable_de_la_oferta__c</description>
    <inlineHelpText>Operation user of the area involved</inlineHelpText>
    <label>Responsable de oferta(Operaciones)</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>El responsable de la oferta tiene que estar dada de alta como gerente en SAP.</errorMessage>
        <filterItems>
            <field>User.Gerente__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Sincronizado_SAP_Ejecucion__c.field-meta.xml
<CustomField>
    <fullName>Sincronizado_SAP_Ejecucion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sincronizado SAP Ejecución</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Sincronizado_SAP_Preventa__c.field-meta.xml
<CustomField>
    <fullName>Sincronizado_SAP_Preventa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sincronizado SAP Preventa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Tecnologia__c.field-meta.xml
<CustomField>
    <fullName>Tecnologia__c</fullName>
    <label>Competencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tecnologias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Validado_para_Sincronizacion__c.field-meta.xml
<CustomField>
    <fullName>Validado_para_Sincronizacion__c</fullName>
    <formula>NOT(ISBLANK(TEXT( Gerencia__c ))) &amp;&amp; 
NOT(ISBLANK(TEXT( Area__c ))) &amp;&amp; 
NOT(ISBLANK(TEXT( Tecnologia__c ))) &amp;&amp;
NOT(ISBLANK( Coste_estimado__c )) &amp;&amp;
NOT(ISBLANK( Fecha_Fin__c )) &amp;&amp;
NOT(ISBLANK( Fecha_Inicio__c )) &amp;&amp;
NOT(ISBLANK( Margen_bruto__c )) &amp;&amp;
Validacion_Crossobject_Sincro__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Required fields: Management, Area, Technology, Estimated Cost, End Date, Start Date, Gross Margin, Proyect Leader of Presales, Proyect Leader of Execution</inlineHelpText>
    <label>Validado para Sincronización</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch_SincronizarLineasDeProyecto.cls
/**
* Clase para sincronizar periódicamente las lineas de proyecto
**
* @author: gserrano (2018/11/16)
*/

global class Batch_SincronizarLineasDeProyecto implements Database.Batchable<sObject>, Schedulable, Database.AllowsCallouts
{
    global String query;

	global Batch_SincronizarLineasDeProyecto()
    {
        //Recupera Lineas de proyectos preventa no sincronizados en SAP con su oportunidad en estado 
        //(preventa, presentada , entregada y ganada)
        //y recupera también lineas de proyecto en ejecución ya sincronizadas como preventa en SAP
        // pero sin sincronizar como ejecución en SAP y que estan validadas y listas para ser enviadas
        query = 'SELECT Id, '
                + 'Name, ' 
                + 'Sincronizado_SAP_Preventa__c, ' 
                + 'Sincronizado_SAP_Ejecucion__c, ' 
                + 'Listo_para_sincronizar__c, ' 
                + 'Validado_para_Sincronizacion__c, ' 
                + 'Codigo_SAP_Preventa__c, ' 
                + 'Codigo_SAP_Ejecucion__c, ' 
                + 'Oportunidad__r.ID_SAP__c, ' 
                + 'Oportunidad__r.StageName, ' 
                + 'Oportunidad__r.Contrato_Firmado__c, '
                + 'Oficina_tecnica__c,'
                + 'Area__c, ' 
                + 'Clave_de_Periodificacion__c, ' 
                + 'Fecha_Fin__c, '
                + 'Fecha_Inicio__c, ' 
                + 'Gerencia__c, ' 
                + 'Jefe_de_Proyecto_de_Preventa__r.Codigo_de_empleado__c, ' 
                + 'Margen_real__c, ' 
                + 'Importe_total_2__c, ' 
                + 'Responsable_de_LDP__r.EmployeeNumber, ' 
                + 'Tecnologia__c, ' 
                + 'Oportunidad__r.Proyecto_extraordinario__c, '
            	+ 'Oportunidad__r.Codigo_de_oportunidad__c, '
                + 'RecordType.developername, ' 
                + 'Oportunidad__r.Oficina_tecnica__c, ' 
                + 'Oportunidad__r.Account.ID_SAP__c, ' 
                + 'Oportunidad__r.Offering__r.EmployeeNumber,'
                + 'Oportunidad__r.Offering__r.Profile.Id,'
                + 'CreatedBy.EmployeeNumber, '
                + 'Nombre_SAP__c,'
                + 'LastModifiedBy.EmployeeNumber'
                +' FROM Linea_de_proyecto__c ';
       
        List<Linea_de_Proyecto__c> lps = Database.query(query);
        System.debug('RESULTADO: ' + lps);
    }

    global Database.queryLocator start(Database.BatchableContext BC)
    { 
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<SObject> scope)
    {
        List<Linea_de_Proyecto__c> lpsPreventa = new List<Linea_de_Proyecto__c>();
        List<Linea_de_Proyecto__c> lpsEjecucion = new List<Linea_de_Proyecto__c>();
        List<String> estadosValidos  = new List<String>{'Preventa','Presentada','Entregada'};
            
        system.debug('DATOS BATCH __ '+scope);
         
        //Variable que utilizaremos más adelante en for, se declara aquí por optimización
        List<Linea_de_proyecto__c> lpsRelacionadas;
        Linea_de_proyecto__c lpTemporal;
        Map<Id, Opportunity> mapOpsRelacionadas;
        
       	//A continuación se recogerán las oportunidades necesarias y se guardarán en un mapa
       	//para posteriormente recuperarlas donde proceda
        
		Set<Id> idsOpsRelacionadas = new set<Id>();
        for(Linea_de_Proyecto__c lp : (List<Linea_de_Proyecto__c>) scope)  
        {
            if
            (//ESTO PARA LOS EJECUCIÓN
               lp.Sincronizado_SAP_Ejecucion__c == false 
               && lp.Validado_para_Sincronizacion__c == true 
               && String.isNotBlank(lp.Codigo_SAP_Preventa__c) 
               && lp.Listo_para_sincronizar__c == true 
               && String.isBlank(lp.Oportunidad__r.ID_SAP__c)
            )
            {
				idsOpsRelacionadas.add(lp.Oportunidad__c);
            }
        }
        
        if(!idsOpsRelacionadas.isEmpty())
        {//SE RECUPERAN LAS OPORTNIDADES CON LP DE EJECUCIÓN
        mapOpsRelacionadas = new Map<Id, Opportunity>
            (
                [SELECT Id, 
                (
                    SELECT Id, 
                    Sincronizado_SAP_Ejecucion__c, 
                    Validado_para_Sincronizacion__c, 
                    Codigo_SAP_Preventa__c, 
                    RecordType.developername,
                    Listo_para_sincronizar__c,
                    Linea_principal__c
                	   FROM Lineas_de_Proyecto__r 
                    WHERE No_aplica_para_ejecucion__c = false
                ),
                Name,
                ID_SAP__c,
                Codigo_de_oportunidad__c,
                Sede_Venta__r.ID_SAP__c,
                Account.ID_SAP__c,
                Contrato_Firmado__c,
                CurrencyIsoCode,
                Owner.EmployeeNumber,
                LastModifiedBy.EmployeeNumber
                FROM Opportunity 
                WHERE Id in :idsOpsRelacionadas]
            );
        }
        
        for(Linea_de_Proyecto__c lp : (List<Linea_de_Proyecto__c>) scope)  
        {
            /*Una misma lp puede cumplir las dos condiciones siguientes*/
            /*Si no está sincronizado en preventa (y la oportunidad está en un estado correspondiente) => enviar preventa*/
            if(lp.Sincronizado_SAP_Preventa__c == false && estadosValidos.contains(lp.Oportunidad__r.StageName))
            {
                lpsPreventa.add(lp);
            } 
            /*Si no está sincronizado en ejecucion y se ha sincronizado alguna vez en preventa y su oportunidad esta firmada(tiene código preventa) -> enviar ejecución*/
            else if(lp.Oportunidad__r.StageName == Constants.OPPORTUNITY_STAGE_WON)
            {//LP PROYECTO Oportunidad ganada
                // if(
                // lp.Sincronizado_SAP_Ejecucion__c == false 
                // && lp.Validado_para_Sincronizacion__c == true 
                // && String.isNotBlank(lp.Codigo_SAP_Preventa__c) 
                // && lp.Listo_para_sincronizar__c == true
                // )
                // {
                //     //incluir condicion: si la Oportunidad de la LP tiene ID_SAP, se envia la LP a SAP
                //     //si la oportunidad no tiene ID_SAP, se pregunta si la linea_de_proyecto_principal de la oportunidad cumpla las condiciones del if de arriba
                //     //y si es así, primero se envia la op a otro servicio (mirar en quip)                
                // if(String.isNotBlank(lp.Oportunidad__r.ID_SAP__c))
                // {
                //     lpsEjecucion.add(lp);
                // }
                // else
                // {
                //     lpsRelacionadas = (List<Linea_de_proyecto__c>) mapOpsRelacionadas.get(lp.Oportunidad__c).get('Lineas_de_proyecto__c');

                //         System.debug('lpsRelacionadas -- > '+ lpsRelacionadas );
                //     for(Linea_de_proyecto__c lpTemp : lpsRelacionadas)
                //     {
                //         if(lpTemp.Linea_principal__c == true)
                //         {
                //             lpTemporal = lpTemp;
                //             break;
                //         }
                //     }
                    
                //     if(lpTemporal != null )
                //     {
                //         if
                //         (
                //                 lp.Sincronizado_SAP_Ejecucion__c == false 
                //                 && lp.Validado_para_Sincronizacion__c == true 
                //                 && String.isNotBlank(lp.Codigo_SAP_Preventa__c) 
                //                 && lp.Listo_para_sincronizar__c == true
                //         )
                //         {
                //                 //Enviar la Lp a SAP pero no hacer DMLs aún
                //                 OpportunityUtil.serializeAndSendOpportunity(new List<Opportunity>{mapOpsRelacionadas.get(lp.Oportunidad__c)}, Constants.SAP_OPPORTUNITIES_PATH, true); //True es POSPONER
                //         }
                //     }
                // }
                // lpsEjecucion.add(lp);
                // }
            }    
        }

        if(!lpsPreventa.isEmpty()) 
        { 
            SYSTEM.debug(lpsPreventa.size());
            system.debug('AQUI');
            ProjectLineUtil.serializeAndSendProjectLines(lpsPreventa, Constants.SAP_LPS_PREVENTA_PATH, null, false);
        } 
        
        if(!lpsEjecucion.isEmpty()) 
        {
            ProjectLineUtil.serializeAndSendProjectLines(lpsEjecucion, Constants.SAP_LPS_EJECUCION_PATH, null, false);
        }
    }

    public static void SchedulerMethod()
    {
        String timeinterval = '0 0 * * * ?';
        System.schedule('Batch_SincronizarLineasDeProyecto',timeinterval, new Batch_SincronizarLineasDeProyecto());
    }

    global void execute(SchedulableContext SC)
    {
        Database.executeBatch(new Batch_SincronizarLineasDeProyecto ());
    } 

    global void finish(Database.BatchableContext BC){}
}