force-app/main/default/objects/Linea_de_Proyecto__c/Linea_de_Proyecto__c.object-meta.xml
<CustomObject>
    <label>Línea de Proyecto</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Número de Línea de Proyecto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Proyecto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Direccion_cliente__c.field-meta.xml
<CustomField>
    <fullName>Direccion_cliente__c</fullName>
    <label>Direccion cliente</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Estimated_date_of_incorporation__c.field-meta.xml
<CustomField>
    <fullName>Estimated_date_of_incorporation__c</fullName>
    <label>Estimated date of incorporation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/n_vacantes__c.field-meta.xml
<CustomField>
    <fullName>n_vacantes__c</fullName>
    <label>No. of vacancies</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Líneas de Proyecto</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Profile_Description__c.field-meta.xml
<CustomField>
    <fullName>Profile_Description__c</fullName>
    <label>Profile Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Sede__c.field-meta.xml
<CustomField>
    <fullName>Sede__c</fullName>
    <defaultValue>if( ISPICKVAL($User.Sede__c ,&apos;1210&apos;),&apos;1210&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1110&apos;),&apos;1110&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Perú&apos;),&apos;VASS Perú&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Colombia&apos;),&apos;VASS Colombia&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS México&apos;),&apos;VASS México&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Chile&apos;),&apos;VASS Chile&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS UK&apos;),&apos;VASS UK&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Benelux&apos;),&apos;VASS Benelux&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1800&apos;),&apos;1800&apos;,&apos;1000&apos;

)))))))))</defaultValue>
    <label>Sede (Delivery Company)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sede</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CornestoneWSTest.cls
@isTest
private class CornestoneWSTest {
    @isTest
    static void testGetConerDataValidDates() {
     Id preventaRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Constants.OPPORTUNITY_RECORDTYPE_PRESALE).getRecordTypeId();

        Opportunity opp1 = new Opportunity(
            Name = 'Opportunity 1',
            RecordTypeId = preventaRecordTypeId,
            StageName = Constants.OPPORTUNITY_STAGE_IDENTIFIED,
            CloseDate = Date.newInstance(2018, 12, 16)
        );

        Opportunity opp2 = new Opportunity(
            Name = 'Opportunity 2',
            RecordTypeId = preventaRecordTypeId,
            StageName = Constants.OPPORTUNITY_STAGE_IDENTIFIED,
            CloseDate = Date.newInstance(2018, 12, 16)
        );

        User u1 = [SELECT Id FROM User  where IsActive=True  and EmployeeNumber !=null LIMIT 1];
        User u2 = [SELECT Id FROM User  where IsActive =True and EmployeeNumber !=null  LIMIT 1];
        //u1 EmployeeNumber = 0012
        //u1 EmployeeNumber = 0013
        Test.startTest();

        System.runAs(u1)
        {
        	insert opp1;
        }

        System.runAs(u2)
        {
            insert opp2;
        }
        RecordType testRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Linea_de_Proyecto__c' LIMIT 1];
        
        Linea_de_Proyecto__c testLine = new Linea_de_Proyecto__c(
            Oportunidad__c = opp1.Id,
            Sede__c = '1000',
            rate__c = 100.0,
            RecordTypeId = testRecordType.Id, 
            Direccion_cliente__c = 'Test Address',
            Profile_Description__c = 'Test Description',
            n_vacantes__c = 3,
            Estimated_date_of_incorporation__c = Date.today().addMonths(2)
        );
        insert testLine;

        // Simular la solicitud REST con parámetros válidos
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetCSODdata';
        req.httpMethod = 'GET';

        RestContext.request = req;
        RestContext.response = res;

        // Llamar al método
        CornestoneWS.getConerData();

        // Validar el resultado
    
        String responseBody = res.responseBody.toString();
      
    }

    @isTest
    static void testGetConerDataInvalidDates() {
        // Simular la solicitud REST con fechas inválidas
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/GetCSODdata';
        req.httpMethod = 'GET';
        req.addParameter('startDate', 'InvalidDate');
        req.addParameter('endDate', 'InvalidDate');
        RestContext.request = req;
        RestContext.response = res;

        // Llamar al método
        CornestoneWS.getConerData();


        String responseBody = res.responseBody.toString();
  
    }


}