force-app/main/default/objects/Historial_Excel_Economico__c/Historial_Excel_Economico__c.object-meta.xml
<CustomObject>
    <label>Historico Excel Económico</label>
    <nameField>
        <displayFormat>HR-{0000}</displayFormat>
        <label>Nombre de Historial Excel Economico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historico Excel Económico</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Historial_Excel_Economico__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Historial_Excel_Econ_mico</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/Linea_de_Proyecto__c.object-meta.xml
<CustomObject>
    <label>Línea de Proyecto</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Número de Línea de Proyecto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Proyecto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Práctica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gerencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Areas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Coste_Bruto__c.field-meta.xml
<CustomField>
    <fullName>Coste_Bruto__c</fullName>
    <label>Total Coste Bruto</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Coste_estimado__c.field-meta.xml
<CustomField>
    <fullName>Coste_estimado__c</fullName>
    <label>Coste estimado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Coste_real__c.field-meta.xml
<CustomField>
    <fullName>Coste_real__c</fullName>
    <formula>Coste_estimado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coste Bruto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Fecha_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin__c</fullName>
    <label>Fecha Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Gerencia__c.field-meta.xml
<CustomField>
    <fullName>Gerencia__c</fullName>
    <label>Área</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Gerencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/GerenciaCode__c.field-meta.xml
<CustomField>
    <fullName>GerenciaCode__c</fullName>
    <formula>CASE(
    Gerencia__c,
    &quot;Estructura&quot;, &quot;N000&quot;,
    &quot;Comercial&quot;, &quot;N001&quot;,
    &quot;Nateevo - Consulting&quot;, &quot;N002&quot;,
    &quot;Nateevo - Experience&quot;, &quot;N003&quot;,
    &quot;Nateevo - Smartech&quot;, &quot;N004&quot;,
    &quot;Nateevo - Development&quot;, &quot;N005&quot;,
    &quot;Nateevo - Brand Services&quot;, &quot;N006&quot;,
    &quot;Nateevo-Business Value&quot;, &quot;N007&quot;,
    &quot;Operaciones&quot;, &quot;N008&quot;,
    &quot;Customer Centric&quot;, &quot;V017&quot;,
    &quot;Digital Experience&quot;, &quot;V002&quot;,
    &quot;Tailor-Made Solutions&quot;, &quot;V003&quot;,
    &quot;Regulatory &amp; Data&quot;, &quot;V004&quot;,
    &quot;Governance &amp; Infrastructure&quot;, &quot;V005&quot;,
    &quot;No utilizar (Consultoría)&quot;, &quot;V006&quot;,
    &quot;Talent Solutions&quot;, &quot;V007&quot;,
    &quot;Operaciones&quot;, &quot;V009&quot;,
    &quot;Innovación (BV)&quot;, &quot;V010&quot;,
    &quot;Proyectos Internos&quot;, &quot;V011&quot;,
    &quot;Comercial&quot;, &quot;V012&quot;,
    &quot;Hybris&quot;, &quot;V013&quot;,
    &quot;Integration &amp; Processes&quot;, &quot;V014&quot;,
    &quot;Delivery Cross&quot;, &quot;V016&quot;,
    &quot;Customer Centric&quot;, &quot;V017&quot;,
    &quot;Business Consulting&quot;, &quot;V018&quot;,
    &quot;Datamorphosys&quot;, &quot;V019&quot;,
    &quot;Staffing (MX)&quot;, &quot;MX20&quot;,
    &quot;Servicios Diversos (Serb)&quot;, &quot;S020&quot;,
    &quot;Customer Experience&quot;, &quot;T002&quot;,
    &quot;Intelligent Technology&quot;, &quot;T005&quot;,
    &quot;S/4&quot;, &quot;T004&quot;,
    &quot;Comunytek&quot;, &quot;V021&quot;,
    &quot;Intelligent Enterprise&quot;, &quot;T001&quot;,
    &quot;Cloud Nine&quot;, &quot;V022&quot;,
    &quot;Nateevo - Delivery Success&quot;, &quot;N011&quot;,
    &quot;Nateevo - Data &amp; Analytics&quot;, &quot;N009&quot;,
    &quot;Nateevo - Media&quot;, &quot;N010&quot;,
    &quot;SAP CX&quot;, &quot;V023&quot;,
&quot;Nateevo Inside VASS&quot;,&quot;V024&quot;,
	&quot;T4S Inside VASS&quot;,&quot;V025&quot;,
    &quot;Sin Asignar&quot;, &quot;V000&quot;,  /* valor adicional si hay duplicados */
    &quot;No definido&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GerenciaCode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Importe_total_2__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_2__c</fullName>
    <description>Nuevo campo para poder indicar de forma manual el importe final</description>
    <label>Importe total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/No_aplica_para_ejecucion__c.field-meta.xml
<CustomField>
    <fullName>No_aplica_para_ejecucion__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this project line does not count towards the pipeline, it will not be synchronized with SAP</inlineHelpText>
    <label>No aplica para ejecución</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Líneas de Proyecto</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Precio_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_Venta__c</fullName>
    <label>Precio Venta</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Sede__c.field-meta.xml
<CustomField>
    <fullName>Sede__c</fullName>
    <defaultValue>if( ISPICKVAL($User.Sede__c ,&apos;1210&apos;),&apos;1210&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1110&apos;),&apos;1110&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Perú&apos;),&apos;VASS Perú&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Colombia&apos;),&apos;VASS Colombia&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS México&apos;),&apos;VASS México&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Chile&apos;),&apos;VASS Chile&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS UK&apos;),&apos;VASS UK&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Benelux&apos;),&apos;VASS Benelux&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1800&apos;),&apos;1800&apos;,&apos;1000&apos;

)))))))))</defaultValue>
    <label>Sede (Delivery Company)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sede</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/recordTypes/AM.recordType-meta.xml
<RecordType>
    <fullName>AM</fullName>
    <active>true</active>
    <label>AM</label>
</RecordType>

force-app/main/default/objects/Linea_de_Proyecto__c/recordTypes/Llave_en_Mano.recordType-meta.xml
<RecordType>
    <fullName>Llave_en_Mano</fullName>
    <active>true</active>
    <label>Llave en Mano</label>
</RecordType>

force-app/main/default/objects/VersionExcel__mdt/VersionExcel__mdt.object-meta.xml
<CustomObject>
    <label>VersionExcel</label>
    <pluralLabel>VersionExcel</pluralLabel>
</CustomObject>

force-app/main/default/classes/CSVProcessor.cls
public with sharing class CSVProcessor {
    public class CSVResult {
        @AuraEnabled public List<String> headers;
        @AuraEnabled public List<Map<String, String>> rows;
        @AuraEnabled public String warningMessage;
        @AuraEnabled public String csvContent;
    }

    @AuraEnabled
    public static CSVResult processCSV(Id documentId, Id opportunityId) {
        CSVResult result = new CSVResult();
        Savepoint sp = Database.setSavepoint();
        try {
            System.debug('INICIO processCSV');
            if (documentId == null || opportunityId == null) {
                System.debug('FALTAN PARÁMETROS');
                throw new AuraHandledException('Document ID and Opportunity ID are required');
            }

            ContentVersion csvFile = [SELECT VersionData FROM ContentVersion 
                                    WHERE ContentDocumentId = :documentId 
                                    AND IsLatest = true 
                                    LIMIT 1];
            
            if (csvFile == null || csvFile.VersionData == null) {
                System.debug('NO SE ENCONTRO EL ARCHIVO');
                throw new AuraHandledException('CSV file not found');
            }

            Blob csvBlob = csvFile.VersionData;
            result.csvContent = EncodingUtil.base64Encode(csvBlob);
            String csvContent = csvBlob.toString();
            List<String> lines = csvContent.replace('\r\n', '\n')
                                         .replace('\r', '\n')
                                         .split('\n');
            
            if (lines.size() < 2) {
                System.debug('CSV VACÍO');
                throw new AuraHandledException('Empty CSV or no data');
            }

            String headerLine = lines[0].trim().replace('\uFEFF', '');
            result.headers = new List<String>();
            for (String h : headerLine.split(';')) {
                result.headers.add(h.trim());
            }

            Integer versionIndex = result.headers.indexOf('ID_FILE');
            if (versionIndex == -1) {
                System.debug('NO HAY COLUMNA ID_FILE');
                throw new AuraHandledException('CSV version column (ID_FILE) not found');
            }
            
            // Validación de versión
            validateCSVVersion(lines, versionIndex);

            Integer opCodeIndex = result.headers.indexOf('OPPCODE');
            if (opCodeIndex == -1) {
                System.debug('NO HAY COLUMNA OPPCODE');
                throw new AuraHandledException('OPPCODE column not found');
            }

            Opportunity opp = [SELECT Codigo_de_oportunidad__c 
                             FROM Opportunity 
                             WHERE Id = :opportunityId 
                             LIMIT 1];
            if (opp == null) {
                throw new AuraHandledException('Opportunity not found');
            }

            result.rows = new List<Map<String, String>>();
            for (Integer i = 1; i < lines.size(); i++) {
                processCSVRow(lines[i], result.headers, opCodeIndex, opp.Codigo_de_oportunidad__c, i+1, result.rows);
            }

            validateProjectLines(opportunityId, result);

            System.debug('FIN processCSV');
            return result;

        } catch (Exception e) {
            System.debug('EXCEPCION EN processCSV: ' + e.getMessage());
            Database.rollback(sp);
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static void validateCSVVersion(List<String> lines, Integer versionIndex) {
        List<VersionExcel__mdt> versions = [SELECT Code__c FROM VersionExcel__mdt LIMIT 1];
        if (versions.isEmpty()) {
            throw new AuraHandledException('Version configuration not found');
        }
        String expectedVersion = versions[0].Code__c;

        for (Integer i = 1; i < lines.size(); i++) {
            List<String> dataRow = lines[i].split(';', -1);
            if (dataRow.size() > versionIndex) {
                String csvVersion = dataRow[versionIndex].trim();
                if (csvVersion != expectedVersion) {
                    AuraHandledException e = new AuraHandledException('Invalid Excel Version');
                    e.setMessage('Invalid Excel Version, please download the latest template');
                    throw e;
                }
            }
        }
    }

    public static void validateProjectLines(Id opportunityId, CSVResult result) {
        List<Linea_de_Proyecto__c> projectLines = [
            SELECT Sede__c, Gerencia__c, Area__c, No_aplica_para_ejecucion__c, RecordTypeId, GerenciaCode__c, RecordType.Name
            FROM Linea_de_Proyecto__c
            WHERE Oportunidad__c = :opportunityId
            AND No_aplica_para_ejecucion__c = false
            AND RecordTypeId NOT IN ('0120N000000UzjmQAC', '0120N000000kPcVQAU', '0120N000000kPcaQAE') 
            AND (Gerencia__c != null OR Gerencia__c != 'Innovación (BV)')
        ];

        Set<String> projectKeys = new Set<String>();
        for (Linea_de_Proyecto__c lp : projectLines) {
            projectKeys.add(getProjectKey(lp));
        }

        Set<String> csvKeys = new Set<String>();
        for (Map<String, String> row : result.rows) {
            csvKeys.add(getCSVKey(row));
        }

        List<Linea_de_Proyecto__c> missingLines = new List<Linea_de_Proyecto__c>();
        for (Linea_de_Proyecto__c lp : projectLines) {
            if (!csvKeys.contains(getProjectKey(lp))) {
                missingLines.add(lp);
            }
        }

        if (!missingLines.isEmpty()) {
            result.warningMessage = 'One or more project lines are missing in CSV';
        }
    }

    private static void processCSVRow(String dataLine, List<String> headers, Integer opCodeIndex, String oppCode, Integer lineNumber, List<Map<String, String>> rows) {
        if (String.isBlank(dataLine)) return;
        List<String> dataRow = dataLine.split(';', -1);
        if (dataRow.size() <= opCodeIndex) {
            throw new AuraHandledException('Incomplete CSV row at line ' + lineNumber);
        }

        // Validar OPPCODE
        if (dataRow[opCodeIndex].trim() != oppCode) {
            AuraHandledException e = new AuraHandledException('The excel OfferCode does not match the Opp offer code');
            e.setMessage('The excel OfferCode does not match the Opp offer code');
            throw e;
        }

        Map<String, String> rowMap = new Map<String, String>();
        for (Integer j = 0; j < headers.size(); j++) {
            rowMap.put(headers[j], j < dataRow.size() ? dataRow[j].trim() : '');
        }
        rows.add(rowMap);
    }

    @AuraEnabled
    public static void updateProjectLines(Id opportunityId, List<Map<String, String>> csvRows, String csvContent) {
        Savepoint sp = Database.setSavepoint();
        try {
            if (String.isBlank(csvContent)) {
                throw new AuraHandledException('csvContent no puede estar vacío.');
            }

            // Agrupar filas CSV por clave de línea de proyecto
            Map<String, List<Map<String, String>>> csvGroups = new Map<String, List<Map<String, String>>>();
            for (Map<String, String> row : csvRows) {
                String key = getCSVKey(row);
                if (!csvGroups.containsKey(key)) {
                    csvGroups.put(key, new List<Map<String, String>>());
                }
                csvGroups.get(key).add(row);
            }

            List<Linea_de_Proyecto__c> lineasProyecto = [
                SELECT Id, Sede__c, Gerencia__c, Area__c, 
                       Precio_Venta__c, Importe_total_2__c, GerenciaCode__c,
                       Coste_Bruto__c, Coste_estimado__c, Coste_real__c, RecordType.Name,
                       fecha_inicio__c, fecha_fin__c
                FROM Linea_de_Proyecto__c
                WHERE Oportunidad__c = :opportunityId
            ];

            List<Linea_de_Proyecto__c> toUpdate = new List<Linea_de_Proyecto__c>();
            for (Linea_de_Proyecto__c lp : lineasProyecto) {
                String key = getProjectKey(lp);
                if (csvGroups.containsKey(key)) {
                    List<Map<String, String>> groupRows = csvGroups.get(key);

                    Decimal totalPrice = 0;
                    Decimal totalCost = 0;
                    
                    for (Map<String, String> row : groupRows) {
                        totalPrice += parseDecimal(row.get('PRICE_ROL'));
                        totalCost += parseDecimal(row.get('COST_ROL'));
                    }
                    
                    lp.Precio_Venta__c = totalPrice;
                    lp.Importe_total_2__c = totalPrice;
                    lp.Coste_Bruto__c = totalCost;
                    lp.Coste_estimado__c = totalCost;

                    toUpdate.add(lp);
                }
            }

            if (!toUpdate.isEmpty()) {
                System.debug('Actualizando ' + toUpdate.size() + ' líneas de proyecto');
                update toUpdate;
                
                // SE GENERA EL HISTÓRICO SOLO SI SE ACTUALIZAN LÍNEAS DE PROYECTO
                crearHistorico(csvContent, 'CSV procesado exitosamente', opportunityId);
            } else {
                System.debug('No hay líneas de proyecto para actualizar');
            }

        } catch (Exception e) {
            System.debug('EXCEPCION EN updateProjectLines: ' + e.getMessage());
            Database.rollback(sp);
            AuraHandledException e2 = new AuraHandledException(e.getMessage());
            e2.setMessage(e.getMessage());
            throw e2;
        }
    }

    private static String getProjectKey(Linea_de_Proyecto__c lp) {
        String key = (lp.Sede__c != null ? lp.Sede__c.trim() : '') + '|' +
                     (lp.Gerencia__c != null ? lp.GerenciaCode__c.trim() : '') + '|' +
                     (lp.Area__c != null ? lp.Area__c.trim() : '');
        if (lp.RecordType.Name != null) {
            if (lp.RecordType.Name == 'AM') {
                key += '|AM';
            } else if (lp.RecordType.Name == 'Llave en Mano') {
                key += '|Llave_en_Mano';
            } else if (lp.RecordType.Name == 'T&M') {
                key += '|T&M';
            }
        }
        return key;
    }

    private static String getCSVKey(Map<String, String> row) {
        String key = (row.get('ID_BUSINESSUNIT') != null ? row.get('ID_BUSINESSUNIT').trim() : '') + '|' +
                     (row.get('ID_SERVICELINE') != null ? row.get('ID_SERVICELINE').trim() : '') + '|' +
                     (row.get('ID_PRACTISE') != null ? row.get('ID_PRACTISE').trim() : '');
        String idType = row.get('DESC_TYPE') != null ? row.get('DESC_TYPE').trim() : '';
        if (idType == 'Managed Services') {
            key += '|AM';
        } else if (idType == 'Project') {
            key += '|Llave_en_Mano';
        } else if (idType == 'T&M') {
            key += '|T&M';
        }
        return key;
    }

    public static Decimal parseDecimal(String value) {
        if (String.isBlank(value)) return 0;
        try {
            return Decimal.valueOf(value.replace(',', '.'));
        } catch (Exception e) {
            System.debug('Error parseando decimal: ' + value);
            AuraHandledException e2 = new AuraHandledException('Invalid Number format in CSV');
            e2.setMessage('Error procesando valor numérico: ' + value);
            throw e2;
        }
    }

    public static Date parseDate(String dateStr) {
        if (String.isBlank(dateStr)) return null;
        try {
            List<String> parts = dateStr.split('/');
            if (parts.size() != 3) return null;
            return Date.newInstance(
                Integer.valueOf(parts[2]), 
                Integer.valueOf(parts[1]), 
                Integer.valueOf(parts[0])
            );
        } catch (Exception e) {
            System.debug('Error parseando fecha: ' + dateStr);
            return null;
        }
    }
@TestVisible
    private static void crearHistorico(String csvContentBase64, String comentarios, Id oppId) {
        try {
            System.debug('INICIO crearHistorico');
            Historial_Excel_Economico__c historico = new Historial_Excel_Economico__c(
                Comentarios__c = comentarios.left(255),
                Oportunidad__c = oppId
            );
            insert historico;

            ContentVersion conVer = new ContentVersion(
                ContentLocation = 'S',
                PathOnClient = 'economic_data_' + System.now().getTime() + '.csv',
                Title = 'Economic_Excel_' + Datetime.now().format('yyyy-MM-dd'),
                VersionData = EncodingUtil.base64Decode(csvContentBase64)
            );
            insert conVer;

            // Se elimina el bucle While porque ContentDocumentId se genera sincrónicamente al hacer insert.
            ContentVersion conVerInserted = [SELECT ContentDocumentId 
                                             FROM ContentVersion 
                                             WHERE Id = :conVer.Id 
                                             LIMIT 1];

            if (conVerInserted == null || conVerInserted.ContentDocumentId == null) {
                throw new AuraHandledException('No se pudo obtener ContentDocumentId.');
            }

            ContentDocumentLink conDocLink = new ContentDocumentLink(
                LinkedEntityId = historico.Id,
                ContentDocumentId = conVerInserted.ContentDocumentId,
                ShareType = 'V',
                Visibility = 'AllUsers'
            );
            insert conDocLink;
            System.debug('FIN crearHistorico');
        } catch (Exception e) {
            System.debug('EXCEPCION EN crearHistorico: ' + e.getMessage());
            throw new AuraHandledException('Error en crearHistorico: ' + e.getMessage());
        }
    }
}