force-app/main/default/objects/Historico_Action_Plan__c/Historico_Action_Plan__c.object-meta.xml
<CustomObject>
    <label>Histórico Action Plan</label>
    <nameField>
        <label>Historico Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historico Action Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Historico Action Plan</relationshipLabel>
    <relationshipName>Historico_Action_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Historico Action Plan</relationshipLabel>
    <relationshipName>Historico_Action_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Historico Action Plan</relationshipLabel>
    <relationshipName>Historico_Action_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Fabricantes__c.field-meta.xml
<CustomField>
    <fullName>Fabricantes__c</fullName>
    <label>Fabricantes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fabricantes_de_Licencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Knowledge_Area__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Area__c</fullName>
    <label>Knowledge Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agile Solutions Tools (Jira)</fullName>
            </value>
            <value>
                <fullName>API Gateway &amp; Integration (Mulesoft, CA (Api Gateway), ApiGee)</fullName>
            </value>
            <value>
                <fullName>Backend Development (Java OpenStack, .Net, Microservices)</fullName>
            </value>
            <value>
                <fullName>Blockchain (Tokenization, SmartContracts, NFTs)</fullName>
            </value>
            <value>
                <fullName>BPM (Appian, Mendix, Pega, Outsystems)</fullName>
            </value>
            <value>
                <fullName>Branding Services</fullName>
            </value>
            <value>
                <fullName>Business Consulting</fullName>
            </value>
            <value>
                <fullName>CIB Solutions (Trading, Clearing, Real Time Market Data, Risk Management)</fullName>
            </value>
            <value>
                <fullName>Cloud Architecture &amp; Data Consultancy &amp; Design</fullName>
            </value>
            <value>
                <fullName>Cognitive Agents (Chatbot, Avatars, Google DialogFlow, IBM Watson)</fullName>
            </value>
            <value>
                <fullName>CRM (Salesforce, Microsoft Dynamics, Siebel)</fullName>
            </value>
            <value>
                <fullName>CyberSecurity</fullName>
            </value>
            <value>
                <fullName>Data Analytics &amp; BI (PowerBI, Azure Data, Snowflake, Qlik)</fullName>
            </value>
            <value>
                <fullName>Data Architecture Cloud &amp; On-Permise (Powercenter, Databricks, Snowflake, Google Cloud, Informatica BDM)</fullName>
            </value>
            <value>
                <fullName>Data Governance &amp; Modeling (IBM Cloud Pack, Informatica)</fullName>
            </value>
            <value>
                <fullName>Digital Business Platforms (Adobe, Liferay)</fullName>
            </value>
            <value>
                <fullName>Digital Consulting</fullName>
            </value>
            <value>
                <fullName>Document Solutions (Documentum, Captiva, xECM)</fullName>
            </value>
            <value>
                <fullName>Ecommerce (Salesforce Commerce, SAP Customer Experience, Magento, Commerce Tools)</fullName>
            </value>
            <value>
                <fullName>Enterprise Search (Elastic Search, SolR)</fullName>
            </value>
            <value>
                <fullName>ERP Solutions (SAP)</fullName>
            </value>
            <value>
                <fullName>Front End Development (Vue, React, Angular)</fullName>
            </value>
            <value>
                <fullName>IA/ML Cloud &amp; IA Custom Solutions (Azure ML, TensorFlow, Keras, Google Vertex, KL30)</fullName>
            </value>
            <value>
                <fullName>Infrastructure Cloud &amp; OnPremise (Terraform, Ansible, Cloud providers, Containers, Openshift, VMWare Tanzu)</fullName>
            </value>
            <value>
                <fullName>IoT (Barbara IoT)</fullName>
            </value>
            <value>
                <fullName>Mobile (Android, IOS, Kotlin, Ionic)</fullName>
            </value>
            <value>
                <fullName>PMO &amp; Agile Offices (Scrum, Project Management)</fullName>
            </value>
            <value>
                <fullName>Portal Enterprise Platform (Oracle Webcenter, Office 365)</fullName>
            </value>
            <value>
                <fullName>Portal Open Source (Magnolia, Wordpress, PHP)</fullName>
            </value>
            <value>
                <fullName>Process Mining (Celonis, Signavio)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mercados</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Nombre_Tarea__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Tarea__c</fullName>
    <label>Nombre Tarea</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Historico Action Plan</relationshipLabel>
    <relationshipName>Historico_Action_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Propietario__c.field-meta.xml
<CustomField>
    <fullName>Propietario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propietario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Historico_Action_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Sede__c.field-meta.xml
<CustomField>
    <fullName>Sede__c</fullName>
    <label>Sede</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sede</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Solucion__c.field-meta.xml
<CustomField>
    <fullName>Solucion__c</fullName>
    <label>Solucion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Soluciones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En progreso</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <label>Abierta</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <label>Completada</label>
            </value>
            <value>
                <fullName>Abierta</fullName>
                <isActive>false</isActive>
                <label>Abierta</label>
            </value>
            <value>
                <fullName>Completada</fullName>
                <isActive>false</isActive>
                <label>Completada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Strategic_Porfolio_BIG7__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Porfolio_BIG7__c</fullName>
    <label>Strategic_Porfolio_BIG7</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Strategic_Porfolio_BIG7</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_Action_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conocer</fullName>
            </value>
            <value>
                <fullName>Presentar</fullName>
            </value>
            <value>
                <fullName>Evento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchHistoricoActionPlan.cls
Global class BatchHistoricoActionPlan implements Database.Batchable<sObject> {
global final string query;

        //Example query, obviously Im sure you might even use another object
    global BatchHistoricoActionPlan(){
        query = Label.Query_Historico_ActionPlan;
    } 

    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC,List<sObject> scope) {
       List<Historico_Action_Plan__c> objs = new List< Historico_Action_Plan__c >();
        Database.DMLOptions dlo = new Database.DMLOptions();
		dlo.OptAllOrNone=false;
         //Assuming the snapshots you want are of Contact dataa
        for(Sobject s : scope){
            Task a = (Task) s;
            
                        
           Historico_Action_Plan__c ht= new Historico_Action_Plan__c();
            if(a.WhatId!=null){
            if(a.whatid.getSObjectType().getDescribe().getName()=='Account'){
                ht.Account__c=a.WhatId;
            }
           if(a.whatid.getSObjectType().getDescribe().getName()=='Opportunity'){
                ht.Oportunidad__c=a.WhatId;
           }}
            if(a.whoid!=null){
            if(a.whoid.getSObjectType().getDescribe().getName()=='Contact'){
                	ht.Contact__c=a.whoid;
            }}
                	ht.Campaign__c=a.Campaing__c;
            

                	ht.CurrencyIsoCode=a.CurrencyIsoCode;
                	ht.Fabricantes__c=a.Fabricantes__c;
                	ht.Fecha_Fin__c=a.ActivityDate;
                	ht.Mercado__c=a.Mercado__c;
                	ht.Propietario__c=a.OwnerId;
                	ht.Sede__c=a.sede__c;
					ht.Solucion__c=a.SolucionTask__c;
                	ht.Status__c=a.Status;
					ht.Type__c=a.type;
       				ht.Nombre_Tarea__c=a.subject;
            		ht.knowledge_Area__c=a.Technology_2__c;
            		ht.Strategic_Porfolio_BIG7__c=a.Strategic_Porfolio_BIG7__c;
            
    		objs.add(ht);
                
            
        }
        
        system.debug('Insert:'+ Database.insert(objs,true));
        system.debug('scope'+Scope);
   }

   global void finish(Database.BatchableContext BC) {
        System.debug(LoggingLevel.WARN,'Batch Job is Complete!!!!!');
   }
}