force-app/main/default/objects/CodMercado__c/CodMercado__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CodMercado</label>
</CustomObject>

force-app/main/default/objects/CodMercado__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <label>Codigo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Hito_de_facturacion__c/Hito_de_facturacion__c.object-meta.xml
<CustomObject>
    <label>Hito de facturación</label>
    <nameField>
        <label>Nombre del hito de facturación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hito de facturación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hito_de_facturacion__c/fields/Linea_de_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Linea_de_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Línea de Proyecto</label>
    <referenceTo>Linea_de_Proyecto__c</referenceTo>
    <relationshipLabel>Hitos de facturación</relationshipLabel>
    <relationshipName>Hitos_de_facturaci_n</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hito_de_facturacion__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Hitos de facturación</relationshipLabel>
    <relationshipName>Hitos_de_facturacion</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/Linea_de_Proyecto__c.object-meta.xml
<CustomObject>
    <label>Línea de Proyecto</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Número de Línea de Proyecto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Proyecto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Práctica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gerencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Areas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Clase_PEP__c.field-meta.xml
<CustomField>
    <fullName>Clase_PEP__c</fullName>
    <formula>if(RecordType.DeveloperName==&apos;Llave_en_Mano&apos;,&apos;ZA&apos;,
if(text(Tipo_de_ingreso__c)==&apos;Por producción&apos;,&apos;ZM&apos;,
if(text(Tipo_de_ingreso__c)==&apos;Fijo mensual&apos;,&apos;ZB&apos;,
if(RecordType.DeveloperName==&apos;Guardias&apos;,&apos;ZN&apos;,
if(RecordType.DeveloperName==&apos;Hosting&apos;,&apos;ZK&apos;,
if(RecordType.DeveloperName==&apos;Licencias&apos;,&apos;ZG&apos;,
if(RecordType.DeveloperName==&apos;Licencias_Renovaci_n&apos;,&apos;ZG&apos;,
if(RecordType.DeveloperName==&apos;Licencias_Servicios&apos;,&apos;ZG&apos;,
if(RecordType.DeveloperName==&apos;TM&apos;,&apos;ZC&apos;,&apos;NONE&apos;


)))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Clase PEP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Codigo_SAP_Ejecucion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP_Ejecucion__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP Ejecución</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Codigo_SAP_Preventa__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP_Preventa__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP Preventa</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Coste_Bruto__c.field-meta.xml
<CustomField>
    <fullName>Coste_Bruto__c</fullName>
    <label>Total Coste Bruto</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Coste_estimado__c.field-meta.xml
<CustomField>
    <fullName>Coste_estimado__c</fullName>
    <label>Coste estimado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Fabricantes__c.field-meta.xml
<CustomField>
    <fullName>Fabricantes__c</fullName>
    <label>Fabricantes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fabricantes_de_Licencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Fecha_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin__c</fullName>
    <label>Fecha Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Gerencia__c.field-meta.xml
<CustomField>
    <fullName>Gerencia__c</fullName>
    <label>Área</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Gerencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Importe_total_2__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_2__c</fullName>
    <description>Nuevo campo para poder indicar de forma manual el importe final</description>
    <label>Importe total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Jefe_de_Proyecto_de_Preventa__c.field-meta.xml
<CustomField>
    <fullName>Jefe_de_Proyecto_de_Preventa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Operation user of the area involved</inlineHelpText>
    <label>Jefe de Proyecto de Preventa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Jefe de Proyecto</value>
        </filterItems>
        <filterItems>
            <field>Contact.Activo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proyectos de Preventa</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Listo_para_sincronizar__c.field-meta.xml
<CustomField>
    <fullName>Listo_para_sincronizar__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Manual check when all the fields required for the execution are completed correctly and are valid to send to SAP.</inlineHelpText>
    <label>Listo para sincronizar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Margen_bruto__c.field-meta.xml
<CustomField>
    <fullName>Margen_bruto__c</fullName>
    <label>Margen bruto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Margen_real__c.field-meta.xml
<CustomField>
    <fullName>Margen_real__c</fullName>
    <label>Margen real</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Margen_Real_Economico__c.field-meta.xml
<CustomField>
    <fullName>Margen_Real_Economico__c</fullName>
    <formula>if( Margen_real__c!=0 ,Margen_real__c,(1-(Coste_Bruto__c/Precio_Venta__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margen Real</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <formula>Text( Oportunidad__r.Mercado__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mercado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Nombre_SAP__c.field-meta.xml
<CustomField>
    <fullName>Nombre_SAP__c</fullName>
    <formula>if(  ISBLANK( NEW_Nombre_SAP__c )  , (LEFT(TRIM(&quot;ES-&quot;+  IF(ISNULL( Oportunidad__r.Account.Nombre_SAP__c ), LEFT(TRIM(Oportunidad__r.Account.Nombre_SAP__c  ) , 11), LEFT(TRIM(Oportunidad__r.Account.Name ) , 11))  +&quot;-&quot;  + &quot;-&quot; + Area_Corta__c +&quot;-&quot;+  RIGHT(Oportunidad__r.Codigo_de_oportunidad__c, 4)  +&quot;-&quot;  +  LEFT(Oportunidad__r.Name, 11)), 40)),NEW_Nombre_SAP__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre_SAP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oficina_tecnica__c.field-meta.xml
<CustomField>
    <fullName>Oficina_tecnica__c</fullName>
    <inlineHelpText>Technical office where the project line will be executed</inlineHelpText>
    <label>Oficina técnica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Oficina_t_cnica</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Líneas de Proyecto</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Org_Ventas__c.field-meta.xml
<CustomField>
    <fullName>Org_Ventas__c</fullName>
    <label>Org Ventas (Delivery Company)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Org_Ventas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Responsable_de_LDP__c.field-meta.xml
<CustomField>
    <fullName>Responsable_de_LDP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>antiguamente era el campo Responsable_de_la_oferta__c</description>
    <inlineHelpText>Operation user of the area involved</inlineHelpText>
    <label>Responsable de oferta(Operaciones)</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>El responsable de la oferta tiene que estar dada de alta como gerente en SAP.</errorMessage>
        <filterItems>
            <field>User.Gerente__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Sede__c.field-meta.xml
<CustomField>
    <fullName>Sede__c</fullName>
    <defaultValue>if( ISPICKVAL($User.Sede__c ,&apos;1210&apos;),&apos;1210&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1110&apos;),&apos;1110&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Perú&apos;),&apos;VASS Perú&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Colombia&apos;),&apos;VASS Colombia&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS México&apos;),&apos;VASS México&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Chile&apos;),&apos;VASS Chile&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS UK&apos;),&apos;VASS UK&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Benelux&apos;),&apos;VASS Benelux&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1800&apos;),&apos;1800&apos;,&apos;1000&apos;

)))))))))</defaultValue>
    <label>Sede (Delivery Company)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sede</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Sincronizado_SAP_Ejecucion__c.field-meta.xml
<CustomField>
    <fullName>Sincronizado_SAP_Ejecucion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sincronizado SAP Ejecución</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Sincronizado_SAP_Preventa__c.field-meta.xml
<CustomField>
    <fullName>Sincronizado_SAP_Preventa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sincronizado SAP Preventa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Tecnologia__c.field-meta.xml
<CustomField>
    <fullName>Tecnologia__c</fullName>
    <label>Competencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tecnologias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Validado_para_Preventa__c.field-meta.xml
<CustomField>
    <fullName>Validado_para_Preventa__c</fullName>
    <formula>NOT(ISBLANK(TEXT( Gerencia__c ))) &amp;&amp;
NOT(ISBLANK(TEXT( Area__c ))) &amp;&amp; 
NOT(ISBLANK(TEXT( Tecnologia__c ))) &amp;&amp;
Validacion_Crossobject_Preventa__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Required fields: Management, Area, Technology, Proyect Leader of Presales</inlineHelpText>
    <label>Validado para Preventa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Validado_para_Sincronizacion__c.field-meta.xml
<CustomField>
    <fullName>Validado_para_Sincronizacion__c</fullName>
    <formula>NOT(ISBLANK(TEXT( Gerencia__c ))) &amp;&amp; 
NOT(ISBLANK(TEXT( Area__c ))) &amp;&amp; 
NOT(ISBLANK(TEXT( Tecnologia__c ))) &amp;&amp;
NOT(ISBLANK( Coste_estimado__c )) &amp;&amp;
NOT(ISBLANK( Fecha_Fin__c )) &amp;&amp;
NOT(ISBLANK( Fecha_Inicio__c )) &amp;&amp;
NOT(ISBLANK( Margen_bruto__c )) &amp;&amp;
Validacion_Crossobject_Sincro__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Required fields: Management, Area, Technology, Estimated Cost, End Date, Start Date, Gross Margin, Proyect Leader of Presales, Proyect Leader of Execution</inlineHelpText>
    <label>Validado para Sincronización</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Venta_Extraordinaria__c.field-meta.xml
<CustomField>
    <fullName>Venta_Extraordinaria__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Venta Extraordinaria</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_generacion_Hitos_Controller.cls
@istest
public class Test_generacion_Hitos_Controller {
    	private static void test_scenario_DMLs() //afterUpdate
    {

        List<Account> accs = TestUtil.generaCuentasTest();
        List<Contact> conts = TestUtil.generaContactosTest(accs);
        List<Opportunity> opps = TestUtil.generaOportunidadesPreventaTest(accs, conts);
        TestUtil.generaLineasLlaveManoTest(opps, conts);

        opps[0].StageName = 'Solicitada'; 
        opps[1].StageName = 'Solicitada'; 
        opps[0].Mercado__c = 'Banca-Banca';
        opps[1].Mercado__c = 'Banca-Banca';
        update opps;

        //HASTA este momento tenemos:
        //3 Cuentas (2 Externas 1 Interna)
        //3 Contactos (2 Ordinarios 1 Jefe de Proyecto)
        //2 Oportunidades del tipo Preventa con 2 hitos cada una, las dos en estado Solicitada
        //2 Lineas de Proyecto del tipo Llave en Mano y con el check listo para sincronizar = true
        opps[0].StageName = 'Preventa';
        opps[1].StageName = 'Preventa';
     
         
        //Al modificar la oportnida a preventa, se deberían enviar aquellas Lineas 
        //marcadas como válidas para preventa = true
        //El metodo encargado de realizar esta taréa es  OpportunityUtil.serializeAndSendProjectLinesPreventa()
        //TestUtil.generaLineasAMTest(opps, conts); 

        List<Account> cuentas = [SELECT Name, ID_SAP__c FROM Account];
        System.debug('Cuentas para TEST '+cuentas);
        System.assertEquals(Cuentas.get(0).ID_SAP__c, '1');
        System.assertEquals(Cuentas.get(1).ID_SAP__c, null);
        //SE habrán creado dos cuentas, la que contiene -ID_SAP distinto de null tiene una LP y será la que se enviará aSAP

        opps[0].StageName = 'Entregada';
        opps[1].StageName = 'Entregada';
        
        opps[0].StageName = 'Presentada';
        opps[1].StageName = 'Presentada';
       

        List<Linea_de_Proyecto__c> preventassincro = [ SELECT 
                                                       Id,
                                                       Oportunidad__r.Account.ID_SAP__c, 
                                                       Validado_para_Preventa__c,
                                                       Validado_para_Sincronizacion__c, 
                                                       Sincronizado_SAP_Preventa__c,
                                                       Sincronizado_SAP_Ejecucion__c,
                                                       Codigo_SAP_Preventa__c,
                                                       Codigo_SAP_Ejecucion__c,
                                                       Listo_para_sincronizar__c,
                                                       Gerencia__c,
                                                       Area__c,
                                                       Tecnologia__c,
                                                       Coste_estimado__c,
                                                       Fecha_Fin__c,
                                                       Fecha_Inicio__c,
                                                       Margen_bruto__c ,  
                                                       Responsable_de_LDP__c
                                                       FROM Linea_de_proyecto__c ];
        preventassincro[0].Fecha_Inicio__c = date.newInstance(2019, 12, 01); 
        preventassincro[1].Fecha_Inicio__c = date.newInstance(2019, 12, 01); 
       	

        opps[0].StageName = 'Ganada';
        opps[1].StageName = 'Ganada';
      

    }
    
              @isTest
    static void testEnvioCorreoEjecucion()
    {


        test_scenario_DMLs();
		
        
        CodMercado__c setting = new CodMercado__c();
        setting.Name = 'Banca-Banca';
        setting.Codigo__c = '20';
        insert setting;
        
        
        //TEST--------------------------------------------------------------------------------------
            Test.startTest();
        List<Linea_de_Proyecto__c> preventassincro = [ SELECT
                                                        Codigo_SAP_Preventa__c,
                                                          Name,
                                                          Nombre_SAP__c,
                                                          tolabel(Area__c),
                                                          tolabel(Oficina_tecnica__c),
                                                          Fecha_Fin__c, 
                                                          Fecha_Inicio__c,
                                                          Gerencia__c,
                                                          RecordType.Name,
                                                          Oportunidad__r.Owner.Email,
                                                          Jefe_de_Proyecto_de_Preventa__r.Codigo_de_empleado__c,
                                                          Margen_real__c,
                                                          Importe_total_2__c,
                                                          Responsable_de_LDP__r.EmployeeNumber,
                                                          Responsable_de_LDP__r.Name,
                                                          Tecnologia__c,
                                                          Oportunidad__r.Proyecto_Padre__c,
                                                          Oportunidad__r.Proyecto_extraordinario__c,
                                                          Oportunidad__r.Codigo_de_oportunidad__c,
                                                          Oportunidad__r.CreatedDate,
                                                          Oportunidad__r.Account.ID_SAP__c,
                                                          Oportunidad__r.Margen_bruto__c,
                                                          Oportunidad__r.Owner.EmployeeNumber,
                                                          Oportunidad__r.Offering__r.EmployeeNumber,
                                                          Oportunidad__r.Offering__r.Profile.Id,
                                                          CreatedById,
                                                          Fabricantes__c,
                                                          Sede__c,
                                                          Coste_Bruto__c,
                                                          Margen_Real_Economico__c,
                                                          Oportunidad__r.Sede_Venta__r.Oficina_tecnica_SAP__c,
                                                          Oportunidad__r.mercado__c,
                                                          Org_Ventas__c,
                                                          Clase_PEP__c,
                                                          Codigo_SAP_Ejecucion__c,
                                                          CurrencyIsoCode,
                                                          Venta_Extraordinaria__c,
                                                          oportunidad__r.Proyecto_estrategico__c,
                                                          Sin_Controlling__c,
                                                          Ejecutado_en_cliente__c,
                                                          Direccion_cliente__c,
                                                          Clave_Periodificacion__c,
                                                          Agile__c,
                                                          Cambio_Alcance__c,
                                                          Sin_Contrato__c,
                                                          ToLabel(Inducido__c),
                                                          CreatedBy.EmployeeNumber,
                                                          Jefe_Proyecto_Ejecucion_Adicional__r.name,
                                                          Jefe_de_Proyecto_de_Ejecucion__r.Name,
                                                          Oportunidad__r.Owner.Name,
                                                          Oportunidad__r.Account.Name,
                                                          Coste_real__c,
                                                          Importe_a_elevar__c
                                                        
                                                        FROM Linea_de_Proyecto__c ];
        
    
	
        Generacion_Hitos_Controller.guardarHitos(preventassincro[0].oportunidad__c,	Generacion_Hitos_Controller.CalculateHitos(preventassincro[0].oportunidad__c,2));
        Generacion_Hitos_Controller.guardarHitos(preventassincro[0].id,	Generacion_Hitos_Controller.CalculateHitos(preventassincro[0].oportunidad__c,2));
        Generacion_Hitos_Controller.ActualizarHitosTabla(preventassincro[0].oportunidad__c,Generacion_Hitos_Controller.CalculateHitos(preventassincro[0].oportunidad__c,2),	Generacion_Hitos_Controller.CalculateHitos(preventassincro[0].oportunidad__c,2));
        system.assertequals([select id from Hito_de_facturacion__c where Linea_de_Proyecto__c=:preventassincro[0].id].size(),2);
    }

}