force-app/main/default/objects/Analitica__c/Analitica__c.object-meta.xml
<CustomObject>
    <label>Analítica</label>
    <nameField>
        <displayFormat>A-{YY}/{MM}-{0000}</displayFormat>
        <label>Nombre de Analítica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analíticas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Analitica__c/fields/Clan__c.field-meta.xml
<CustomField>
    <fullName>Clan__c</fullName>
    <label>Clan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gerencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Consejo__c.field-meta.xml
<CustomField>
    <fullName>Consejo__c</fullName>
    <label>Consejo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Areas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Analíticas</relationshipLabel>
    <relationshipName>Analiticas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Linea_de_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Linea_de_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Línea de Proyecto</label>
    <referenceTo>Linea_de_Proyecto__c</referenceTo>
    <relationshipLabel>Analíticas</relationshipLabel>
    <relationshipName>Analiticas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Analíticas</relationshipLabel>
    <relationshipName>Analiticas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Propietario__c.field-meta.xml
<CustomField>
    <fullName>Propietario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propietario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Analiticas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <defaultValue>$RecordType.Name</defaultValue>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cierre</fullName>
                <color>#57F17C</color>
                <label>Cierre</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
                <color>#2F5D85</color>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>ForecastDeLinea</fullName>
                <color>#B6E32E</color>
                <label>ForecastDeLinea</label>
            </value>
            <value>
                <fullName>ForecastDeOportunidades</fullName>
                <color>#FF6600</color>
                <label>ForecastDeOportunidades</label>
            </value>
            <value>
                <fullName>Presupuesto</fullName>
                <color>#FF99FF</color>
                <label>Presupuesto</label>
            </value>
            <value>
                <fullName>ForecastImporteTotal_Presupuesto</fullName>
            </value>
            <value>
                <fullName>ForecastImporteXprob_Presupuesto</fullName>
            </value>
            <value>
                <fullName>Backlog Temporal</fullName>
                <color>#3366FF</color>
                <label>Backlog Temporal</label>
            </value>
            <value>
                <fullName>Pipeline</fullName>
                <color>#FF6600</color>
                <label>Pipeline</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Tipo_de_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Proyecto__c</fullName>
    <label>Tipo de Proyecto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Llave en Mano</fullName>
            </value>
            <value>
                <fullName>Licencias</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
            <value>
                <fullName>Venta de licencias</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/Linea_de_Proyecto__c.object-meta.xml
<CustomObject>
    <label>Línea de Proyecto</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Número de Línea de Proyecto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Proyecto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Práctica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gerencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Areas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Duracion_de_linea__c.field-meta.xml
<CustomField>
    <fullName>Duracion_de_linea__c</fullName>
    <formula>Fecha_Fin__c - Fecha_Inicio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duración de línea</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Gerencia__c.field-meta.xml
<CustomField>
    <fullName>Gerencia__c</fullName>
    <label>Área</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Gerencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Importe_prorrateado_x_prob__c.field-meta.xml
<CustomField>
    <fullName>Importe_prorrateado_x_prob__c</fullName>
    <formula>Importe_x_Prob__c / Duracion_de_linea__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Importe prorrateado x prob</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/No_aplica_para_ejecucion__c.field-meta.xml
<CustomField>
    <fullName>No_aplica_para_ejecucion__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this project line does not count towards the pipeline, it will not be synchronized with SAP</inlineHelpText>
    <label>No aplica para ejecución</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Líneas de Proyecto</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Job_Analitica.cls
/**
*@description: job que realiza la creación de analíticas para el forecast
*@param name Description:
*@author name: arodriguez
*@date date: 12/03/2019
*@throws Exception: 
*@where description: 
*@see class/method:
**/  
global class Job_Analitica implements Schedulable
{
    global void execute(SchedulableContext ctx) 
    {
        System.debug('Ejecutando actualización de Analitica__c a día y hora: ' + System.now());
        List<Analitica__c> analist = new List<Analitica__c>(); 

        List<Analitica__c> anadelete = [SELECT Id FROM Analitica__c WHERE Tipo__c = 'Forecast'];

        System.enqueueJob(new Queueable_DMLSObjects(anadelete, Queueable_DMLSObjects.Operation.BORRA));

        For(Linea_de_Proyecto__c LP:[SELECT Id, Gerencia__c, Area__c, CurrencyISOCode, Oportunidad__r.OwnerId, RecordType.Name, Oportunidad__r.AccountId, Duracion_de_Linea__c, Importe_prorrateado_x_prob__c, Fecha_Inicio__c FROM Linea_de_Proyecto__c WHERE No_aplica_para_ejecucion__c = FALSE])
        {
            For(Integer i = 0 ; i<LP.Duracion_de_linea__c ; i++)
            {
                Analitica__c analitica = new Analitica__c();
                analitica.Clan__c = LP.Gerencia__c;
                analitica.Consejo__c = LP.Area__c;
                analitica.Cuenta__c = LP.Oportunidad__r.AccountId;
                analitica.CurrencyISOCode = LP.CurrencyISOCode;
                analitica.Linea_de_Proyecto__c = LP.Id;
                analitica.Propietario__c = LP.Oportunidad__r.OwnerId;
                analitica.Tipo__c = 'Forecast';
                analitica.Tipo_de_Proyecto__c = LP.RecordType.Name;
                analitica.Fecha__c = LP.Fecha_Inicio__c.addMonths(i);
                system.debug(i + ' ' + analitica);
                analist.add(analitica);
            }
        }

        For(Opportunity Opp:[SELECT Id, OwnerId, AccountId, CurrencyISOCode, Duracion_del_proyecto__c, Fecha_de_inicio__c FROM Opportunity])
        {
            For(Integer i = 0 ; i<Opp.Duracion_del_proyecto__c ; i++)
            {
                Analitica__c analitica = new Analitica__c();
                analitica.Cuenta__c = Opp.AccountId;
                analitica.CurrencyISOCode = Opp.CurrencyISOCode;
                analitica.Oportunidad__c = Opp.Id;
                analitica.Propietario__c = Opp.OwnerId;
                analitica.Tipo__c = 'Forecast';
                analitica.Fecha__c = Opp.Fecha_de_inicio__c.addMonths(i);
                system.debug(i + ' ' + analitica);
                analist.add(analitica);
            }
        }
        
        System.enqueueJob(new Queueable_DMLSObjects(analist, Queueable_DMLSObjects.Operation.INSERTA));

    }
}