force-app/main/default/objects/Analitica__c/Analitica__c.object-meta.xml
<CustomObject>
    <label>Analítica</label>
    <nameField>
        <displayFormat>A-{YY}/{MM}-{0000}</displayFormat>
        <label>Nombre de Analítica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analíticas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Analitica__c/fields/Clan__c.field-meta.xml
<CustomField>
    <fullName>Clan__c</fullName>
    <label>Clan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Gerencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Analíticas</relationshipLabel>
    <relationshipName>Analiticas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Importe__c.field-meta.xml
<CustomField>
    <fullName>Importe__c</fullName>
    <label>Importe Backlog</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sectores</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Analíticas</relationshipLabel>
    <relationshipName>Analiticas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Propietario__c.field-meta.xml
<CustomField>
    <fullName>Propietario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Propietario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Analiticas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Sede_Venta__c.field-meta.xml
<CustomField>
    <fullName>Sede_Venta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sede Venta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Analíticas (Sede Venta)</relationshipLabel>
    <relationshipName>Anal_ticas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <defaultValue>$RecordType.Name</defaultValue>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cierre</fullName>
                <color>#57F17C</color>
                <label>Cierre</label>
            </value>
            <value>
                <fullName>Backlog</fullName>
                <color>#2F5D85</color>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>ForecastDeLinea</fullName>
                <color>#B6E32E</color>
                <label>ForecastDeLinea</label>
            </value>
            <value>
                <fullName>ForecastDeOportunidades</fullName>
                <color>#FF6600</color>
                <label>ForecastDeOportunidades</label>
            </value>
            <value>
                <fullName>Presupuesto</fullName>
                <color>#FF99FF</color>
                <label>Presupuesto</label>
            </value>
            <value>
                <fullName>ForecastImporteTotal_Presupuesto</fullName>
            </value>
            <value>
                <fullName>ForecastImporteXprob_Presupuesto</fullName>
            </value>
            <value>
                <fullName>Backlog Temporal</fullName>
                <color>#3366FF</color>
                <label>Backlog Temporal</label>
            </value>
            <value>
                <fullName>Pipeline</fullName>
                <color>#FF6600</color>
                <label>Pipeline</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Analitica__c/recordTypes/Pipeline.recordType-meta.xml
<RecordType>
    <fullName>Pipeline</fullName>
    <active>true</active>
    <label>Pipeline2</label>
</RecordType>

force-app/main/default/classes/Batch_Pipeline_Analitica.cls
global  class  Batch_Pipeline_Analitica  implements  Database.Batchable<SObject>, Schedulable, Database.AllowsCallouts, Database.Stateful{

    global final string query;
    global Batch_Pipeline_Analitica() {

        query = Label.Query_Batch_Pipeline;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        List<analitica__c> Borradoprevio=[Select id from analitica__c where tipo__c='Pipeline'];
        delete(Borradoprevio);
        return Database.getQueryLocator(query);
    }
  
  
  global void execute(Database.BatchableContext BC,List<sObject> scope) {

        list<analitica__c> nuevas= new list<analitica__c>();
        Id PipeRecordTypeId = Schema.SObjectType.analitica__c.getRecordTypeInfosByName().get('Pipeline').getRecordTypeId();
        for(Sobject op : scope){
            Opportunity oportunidad = (Opportunity) op;
            analitica__c nueva= new analitica__c();
            nueva.RecordTypeid= PipeRecordTypeId;      
            nueva.importe__c=oportunidad.Importe_total__c;
            nueva.Clan__c =oportunidad.Clan_Principal__c;
            nueva.Oportunidad__c=oportunidad.id;
            nueva.Fecha__c=oportunidad.closedate;
            nueva.Propietario__c=oportunidad.OwnerId;
            nueva.tipo__c='Pipeline';
            nueva.Cuenta__c=oportunidad.AccountId;
            nueva.Mercado__c=oportunidad.Mercado__c;
            nueva.Sede_Venta__c=oportunidad.Sede_Venta__c;
            nueva.CurrencyIsoCode=oportunidad.CurrencyIsoCode;
            nuevas.add(nueva);
       }
    
      Database.SaveResult[] srList  =Database.insert(nuevas,false);
      for (Database.SaveResult sr : srList) {
        if (sr.isSuccess()) {
        }
        else {
        // Operation failed, so get all errors                
        for(Database.Error err : sr.getErrors()) {
        System.debug('The following error has occurred.');                    
        System.debug(err.getStatusCode() + ': ' + err.getMessage());
        System.debug('Account fields that affected this error: ' + err.getFields());
        }
        }
    }
    
  }
  
    global void finish(Database.BatchableContext BC) {
        System.debug(LoggingLevel.WARN,'Batch Job is Complete!!!!!');
 }
    global void execute(SchedulableContext sc) 
        {

        Batch_Pipeline_Analitica batch = new Batch_Pipeline_Analitica(); 
        ID batchprocessid = Database.executeBatch(Batch); 
        }
}