force-app/main/default/objects/Analitica__c/Analitica__c.object-meta.xml
<CustomObject>
    <label>Analítica</label>
    <nameField>
        <displayFormat>A-{YY}/{MM}-{0000}</displayFormat>
        <label>Nombre de Analítica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analíticas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Analitica__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Analíticas</relationshipLabel>
    <relationshipName>Analiticas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Duplicatefield__c.field-meta.xml
<CustomField>
    <fullName>Duplicatefield__c</fullName>
    <formula>Linea_de_Proyecto__c + text( Importe_Forecast__c) + text(Fecha__c) + Sede_Venta__c + Cuenta__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duplicatefield</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Importe_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Importe_Forecast__c</fullName>
    <label>Importe Forecast</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Analitica__c/recordTypes/ForecastDeLinea.recordType-meta.xml
<RecordType>
    <fullName>ForecastDeLinea</fullName>
    <active>true</active>
    <description>OPPS&gt;70%</description>
    <label>ForecastDeLinea</label>
</RecordType>

force-app/main/default/classes/DeleteDuplicateRecordsBatchTest.cls
@isTest
public class DeleteDuplicateRecordsBatchTest {

    @isTest
    static void testBatchDeleteDuplicates() {
        // Crear registros de prueba
        List<Analitica__c> testRecords = new List<Analitica__c>();
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;
        // Agregamos algunos registros con el mismo valor en el campo Duplicatefield__c para simular duplicados
        testRecords.add(new Analitica__c(Importe_Forecast__c = 1,cuenta__c=testAccount.id, RecordTypeId = Schema.getGlobalDescribe().get('Analitica__c').getDescribe().getRecordTypeInfosByName().get('ForecastDeLinea').getRecordTypeId()));
        testRecords.add(new Analitica__c(Importe_Forecast__c = 1,cuenta__c=testAccount.id, RecordTypeId = Schema.getGlobalDescribe().get('Analitica__c').getDescribe().getRecordTypeInfosByName().get('ForecastDeLinea').getRecordTypeId()));
        testRecords.add(new Analitica__c(Importe_Forecast__c = 1, cuenta__c=testAccount.id,RecordTypeId = Schema.getGlobalDescribe().get('Analitica__c').getDescribe().getRecordTypeInfosByName().get('ForecastDeLinea').getRecordTypeId()));
        testRecords.add(new Analitica__c(Importe_Forecast__c = 2,cuenta__c=testAccount.id, RecordTypeId = Schema.getGlobalDescribe().get('Analitica__c').getDescribe().getRecordTypeInfosByName().get('ForecastDeLinea').getRecordTypeId()));
        testRecords.add(new Analitica__c(Importe_Forecast__c = 3,cuenta__c=testAccount.id, RecordTypeId = Schema.getGlobalDescribe().get('Analitica__c').getDescribe().getRecordTypeInfosByName().get('ForecastDeLinea').getRecordTypeId()));
        
        // Insertamos los registros de prueba
        insert testRecords;

        // Ejecutar el batch
        DeleteDuplicateRecordsBatch batch = new DeleteDuplicateRecordsBatch('Duplicatefield__c');
        Database.executeBatch(batch);

        // Verificar los resultados
        List<Analitica__c> remainingRecords = [
            SELECT Id, Duplicatefield__c 
            FROM Analitica__c 
            WHERE RecordType.Name = 'ForecastDeLinea'
        ];

        // Comprobar que solo queda un registro por cada valor único en el campo Duplicatefield__c
        Map<String, Integer> recordCountByField = new Map<String, Integer>();
        for (Analitica__c record : remainingRecords) {
            if (!recordCountByField.containsKey(record.Duplicatefield__c)) {
                recordCountByField.put(record.Duplicatefield__c, 0);
            }
            recordCountByField.put(record.Duplicatefield__c, recordCountByField.get(record.Duplicatefield__c) + 1);
        }

     
    }
}