force-app/main/default/objects/Analitica__c/Analitica__c.object-meta.xml
<CustomObject>
    <label>Analítica</label>
    <nameField>
        <displayFormat>A-{YY}/{MM}-{0000}</displayFormat>
        <label>Nombre de Analítica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analíticas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Analitica__c/fields/Importe_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Importe_Forecast__c</fullName>
    <label>Importe Forecast</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Importe_x_Prob__c.field-meta.xml
<CustomField>
    <fullName>Importe_x_Prob__c</fullName>
    <formula>IF( AND(Fecha_de_cierre__c &lt; DATE(YEAR(TODAY()) , MONTH(TODAY()) , 01),ISPICKVAL(Tipo__c,&apos;Forecast&apos;)) , 0 , 
IF(NOT(ISBLANK(Linea_de_Proyecto__c)),Linea_de_Proyecto__r.Importe_prorrateado_x_prob__c, 
IF(NOT(ISBLANK(Oportunidad__c)),Oportunidad__r.Importe_prorrateado__c * Probabilidad__c, 
IF(ISPICKVAL(Tipo__c,&apos;Ingresos vs costes&apos;),Ingresos_Reales__c,Importe__c))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Importe x Prob</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Linea_de_Proyecto__c.field-meta.xml
<CustomField>
    <fullName>Linea_de_Proyecto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Línea de Proyecto</label>
    <referenceTo>Linea_de_Proyecto__c</referenceTo>
    <relationshipLabel>Analíticas</relationshipLabel>
    <relationshipName>Analiticas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sectores</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Oficina_Tecnica__c.field-meta.xml
<CustomField>
    <fullName>Oficina_Tecnica__c</fullName>
    <label>Oficina Tecnica</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Oficina_t_cnica</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Analíticas</relationshipLabel>
    <relationshipName>Analiticas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Sede_Venta__c.field-meta.xml
<CustomField>
    <fullName>Sede_Venta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sede Venta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Analíticas (Sede Venta)</relationshipLabel>
    <relationshipName>Anal_ticas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/Linea_de_Proyecto__c.object-meta.xml
<CustomObject>
    <label>Línea de Proyecto</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Número de Línea de Proyecto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Proyecto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Práctica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gerencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Areas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Coste_real__c.field-meta.xml
<CustomField>
    <fullName>Coste_real__c</fullName>
    <formula>Coste_estimado__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coste Bruto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Duracion_de_linea__c.field-meta.xml
<CustomField>
    <fullName>Duracion_de_linea__c</fullName>
    <formula>Fecha_Fin__c - Fecha_Inicio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duración de línea</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Duracion_lineas_por_meses__c.field-meta.xml
<CustomField>
    <fullName>Duracion_lineas_por_meses__c</fullName>
    <formula>IF( 
(Fecha_Fin__c - Fecha_Inicio__c) / 365 * 12 &lt; 1, 1, (Fecha_Fin__c - Fecha_Inicio__c ) / 365 * 12)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duración lineas por meses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Fecha_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin__c</fullName>
    <label>Fecha Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Gerencia__c.field-meta.xml
<CustomField>
    <fullName>Gerencia__c</fullName>
    <label>Área</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Gerencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Importe_a_elevar__c.field-meta.xml
<CustomField>
    <fullName>Importe_a_elevar__c</fullName>
    <formula>if(AND( Precio_Venta__c &gt;1 &amp;&amp;Intercompany__c==false &amp;&amp;Importe_de_licencias__c==0 )  ,Precio_Venta__c + Importe_de_licencias__c,
if(Intercompany__c==true, Importe_Total_Intercompany__c ,
if(Importe_de_licencias__c&gt;0,Importe_de_licencias__c,Importe_total_2__c + Importe_de_licencias__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Importe a elevar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Importe_prorrateado_x_prob__c.field-meta.xml
<CustomField>
    <fullName>Importe_prorrateado_x_prob__c</fullName>
    <formula>Importe_x_Prob__c / Duracion_de_linea__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Importe prorrateado x prob</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Importe_total_2__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_2__c</fullName>
    <description>Nuevo campo para poder indicar de forma manual el importe final</description>
    <label>Importe total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Importe_total__c.field-meta.xml
<CustomField>
    <fullName>Importe_total__c</fullName>
    <formula>(Coste_estimado__c / (1 - Margen_bruto__c)) + Importe_de_licencias__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Importe total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Importe_x_Prob__c.field-meta.xml
<CustomField>
    <fullName>Importe_x_Prob__c</fullName>
    <formula>Importe_a_elevar__c *  Oportunidad__r.Probability</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Importe x Prob</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <formula>Text( Oportunidad__r.Mercado__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mercado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/No_aplica_para_ejecucion__c.field-meta.xml
<CustomField>
    <fullName>No_aplica_para_ejecucion__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this project line does not count towards the pipeline, it will not be synchronized with SAP</inlineHelpText>
    <label>No aplica para ejecución</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oficina_tecnica__c.field-meta.xml
<CustomField>
    <fullName>Oficina_tecnica__c</fullName>
    <inlineHelpText>Technical office where the project line will be executed</inlineHelpText>
    <label>Oficina técnica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Oficina_t_cnica</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Líneas de Proyecto</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Responsable_de_LDP__c.field-meta.xml
<CustomField>
    <fullName>Responsable_de_LDP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>antiguamente era el campo Responsable_de_la_oferta__c</description>
    <inlineHelpText>Operation user of the area involved</inlineHelpText>
    <label>Responsable de oferta(Operaciones)</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>El responsable de la oferta tiene que estar dada de alta como gerente en SAP.</errorMessage>
        <filterItems>
            <field>User.Gerente__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_Forecast_Rafa.cls
@isTest

public class Test_Forecast_Rafa{
    // ******************* TEST INDIVIDUALES Y CASOS ESPECIALES ******************* 
    // 
    
       public static User u1;
    public static User u2;
    public static User u3;
    public static User u4;
    public static User u5;
    public static User u6;
    public static User u7;
    
    @isTest
    static void ForecastImpxprob() 
    {
        // Insertar 5 usuarios
        Id comercialProfileId = [SELECT Id FROM Profile WHERE Name = 'Comercial'].Id;
        Id adminProfileId = [SELECT Id FROM Profile WHERE Name = 'Administrador del sistema' OR Name = 'System administrator'].Id;
        Id gerenteOperacionesRolId = [SELECT Id FROM UserRole WHERE DeveloperName = 'Gerente_de_operaciones'].Id;        
        Id responsableAreaRolId = [SELECT Id FROM UserRole WHERE DeveloperName = 'Responsable_de_area'].Id;
        User admin = [SELECT Id FROM User WHERE ProfileId =: adminProfileId AND IsActive = true LIMIT 1];
       
       System.runAs(admin){
         u1 = new User(
            ProfileId = comercialProfileId,
            LastName = 'last',
            Email = 'resp1@vass.com',
            Username = 'resp1@vass.com.' + System.currentTimeMillis(),
            CompanyName = 'ExampleCompany',
            Title = 'Title',
            Alias = 'Alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            Gerente__c=True,
            LocaleSidKey = 'en_US'
        );
        insert u1;
        
     
       //*******************************************/
       }
		List<Account> accs = TestUtil.generaCuentasTest();
        // Insertar dos oportunidades
        Id preventaRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Constants.OPPORTUNITY_RECORDTYPE_PRESALE).getRecordTypeId();

        List<Opportunity> opptys = new List<Opportunity>();
        
		List<Opportunity> opptys2 = new List<Opportunity>();
        
        Opportunity opp1 = new Opportunity(
            Name = 'Opportunity 1',
            RecordTypeId = preventaRecordTypeId,
            StageName = Constants.OPPORTUNITY_STAGE_IDENTIFIED,
            CloseDate = Date.newInstance(2018, 12, 16),
            Bid_Manager__c = u1.Id,
            Offering__c = u1.Id,
            Business_Value__c = u1.Id,
            Mercado__c='Banca-Banca',
            Probability=50,
            Amount=99,
            AccountId=accs.get(0).id
        );
        
        opptys.add(opp1);

        insert opptys;

 
              
        insert opptys2;
        
        opp1 = [SELECT Id FROM Opportunity WHERE Name = 'Opportunity 1'];
        
        // Insertar cuatro lineas de proyecto
        List<Linea_de_Proyecto__c> projectLines = new List<Linea_de_Proyecto__c>();
        
        projectLines.add(new Linea_de_Proyecto__c(
            Oportunidad__c = opp1.Id,
            Responsable_de_LDP__c = u1.Id,
            Fecha_Inicio__c=date.newInstance(2019, 01, 01),
            Fecha_Fin__c=date.newInstance(2019, 01, 30),
            Oficina_tecnica__c='1000',
            Importe_total_2__c=8000
            
        ));
 
      
 		
        insert projectLines;
        
     
     integer i=0;
     List<Linea_de_Proyecto__c>   linea = new List<Linea_de_Proyecto__c>();
    List<Opportunity>   Oportunidad1 = new List<Opportunity>();

     integer prob =0;




                            linea = [SELECT   Id,
                                                    Gerencia__c,
                                                    Area__c, 
                                                    CurrencyISOCode,
                                                    Oportunidad__r.OwnerId,
                                                    RecordType.Name, 
                                                    Oportunidad__r.AccountId,
                                                    Duracion_de_Linea__c, 
                                                    Importe_prorrateado_x_prob__c, 
                                                    Fecha_Inicio__c,
                                                    Fecha_Fin__c,
                                                    Duracion_lineas_por_meses__c,
                                                    Importe_a_elevar__c,
                                                    Coste_real__c,
                                                    Oportunidad__c,
                                                    Oportunidad__r.probability,
                                                    Oportunidad__r.Sede_Venta__c,
                                                    Oportunidad__r.Owner.Name,
                                                    Oportunidad__r.Multibooking__c,
                                                    Oportunidad__r.mercado__c,
                                                    Importe_x_Prob__c 
                            from Linea_de_Proyecto__c WHERE Oportunidad__c = :opp1.id
                           

                                ];
  			Oportunidad1 = [SELECT   Id,probability,StageName  ,Importe_total__c,Fecha_de_fin__c,Fecha_de_inicio__c,Multibooking__c from Opportunity  where Id= :opp1.id];

   		  map<Id,Opportunity>  oportunidad = new map<Id,Opportunity> ();
        
        oportunidad.put(Oportunidad1.get(0).Id, Oportunidad1.get(0));
     
       

		ForecastRafa.GenerarForecastNuevasLineas(linea, 'opor');
             
    
        Analitica__c analitica = [SELECT Id ,Importe_Forecast__c FROM Analitica__c WHERE   Oportunidad__c =:opp1.id];

        test.startTest();
		ForecastRafa.serializeandGenerateForecastLinea ([SELECT Id FROM Linea_de_Proyecto__c WHERE No_aplica_para_ejecucion__c = FALSE and id='a021X000001xk1cQAA' ] , 'Linea');
        test.stopTest();
        system.assert(analitica.Importe_Forecast__c >0);
        system.assertEquals(ForecastRafa.CumpleCondicionesOportunidadForecast(Oportunidad1,oportunidad),0);
      


    }
    
    
    
    
    
    

    

}