force-app/main/default/objects/Analitica__c/Analitica__c.object-meta.xml
<CustomObject>
    <label>Analítica</label>
    <nameField>
        <displayFormat>A-{YY}/{MM}-{0000}</displayFormat>
        <label>Nombre de Analítica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analíticas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Analitica__c/fields/Consejo__c.field-meta.xml
<CustomField>
    <fullName>Consejo__c</fullName>
    <label>Consejo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Areas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Analíticas</relationshipLabel>
    <relationshipName>Analiticas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripcion</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Importe__c.field-meta.xml
<CustomField>
    <fullName>Importe__c</fullName>
    <label>Importe Backlog</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Analitica__c/recordTypes/Backlog.recordType-meta.xml
<RecordType>
    <fullName>Backlog</fullName>
    <active>true</active>
    <label>Backlog</label>
</RecordType>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0000000}</displayFormat>
        <label>Nombre de log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Test_Queueable_Analytics.cls
@isTest
public class Test_Queueable_Analytics
{

    @testSetup
    static void test_setup(){
        
        Account acc = new Account();
        acc.name = 'Setup1';
        acc.RecordTypeID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(Constants.ACCOUNT_RECORDTYPE_INTERNAL).getRecordTypeId();
        acc.sede__c = '1000';
        acc.NIF_CIF__c = '3';
        acc.ID_SAP__c = '2';
        insert acc;
    }


    @isTest
    public static void test_Queueable_Analytics_SaveResultError()
    {
        List<Account> listAccounts =  [SELECT id FROM Account];
        List<Analitica__c> analiticas = new List<Analitica__c>();
        Analitica__C analitica = new Analitica__C(Cuenta__c = listAccounts[0].id,
        RecordTypeId = Schema.SObjectType.Analitica__c.getRecordTypeInfosByDeveloperName().get('Backlog').RecordTypeId,
        Descripcion__c = 'Test',
        Fecha__c = Date.today(),
        importe__c = 85,
        CurrencyIsoCode = 'EUR',
        Consejo__c = 'ES000K500000');
        analiticas.add(analitica);
        Test.startTest();
        System.enqueueJob(new Queueable_Analytics(analiticas));
        Test.stopTest();

        List<Log__c> logs =  [SELECT id FROM Log__c];
        System.AssertEquals(logs.isEmpty(),false);
    }
}