force-app/main/default/objects/Analitica__c/Analitica__c.object-meta.xml
<CustomObject>
    <label>Analítica</label>
    <nameField>
        <displayFormat>A-{YY}/{MM}-{0000}</displayFormat>
        <label>Nombre de Analítica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analíticas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Analitica__c/recordTypes/Backlog.recordType-meta.xml
<RecordType>
    <fullName>Backlog</fullName>
    <active>true</active>
    <label>Backlog</label>
</RecordType>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{0000000}</displayFormat>
        <label>Nombre de log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <label>Error</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Metodo__c.field-meta.xml
<CustomField>
    <fullName>Metodo__c</fullName>
    <label>Metodo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Backlog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Queueable_Analytics.cls
public without sharing  class Queueable_Analytics implements Queueable {
    
    public List<sObject> sObjectList;  
    public List<Log__c> errorLogs = new List<Log__c>();
    

   public Queueable_Analytics(List<sObject> sObjectListInput) {
       this.sObjectList = sObjectListInput;
   }

   public void execute(QueueableContext context) {
       try{
           if(!sObjectList.isEmpty()){
                insertObjects(sObjectList);
           }

       }catch(Exception ex){
                Log__c errorLog = new Log__c();
                errorLog.Error__c = 'Error creando analíticas '+ex.getCause()+'/'+ex.getMessage();
                errorlog.Type__C = 'Backlog';
                errorlog.Metodo__c = 'CreateAnalytics';
                errorLogs.add(errorLog); 
       }
   }


   /**
    * @author Adrián Bernardo
    * description Inserta los registros que le lleguen de tipo Log__C o Analitica__c y.
    * date 14/03/2023
    */
    public void insertObjects(List<sObject> sObjectsList){
    Schema.SObjectType sobjectType = sObjectsList.get(0).getSObjectType();

    if(sobjectType == Analitica__c.getSObjectType()){
        List<Database.SaveResult> sresultList =  Database.insert((List<Analitica__c>)sObjectsList,false);
        
        for (Database.SaveResult sr : sresultList) {
        if (!sr.isSuccess()) {
            for(Database.Error err : sr.getErrors()) {
                 	Log__c errorLog = new Log__c();
                	errorLog.Error__c = 'Error creando analíticas '+err.getStatusCode() + ': ' + err.getMessage()+': '+err.getFields();
                	errorlog.Type__C = 'Backlog';
                	errorlog.Metodo__c = 'CreateAnalytics';
                	errorLogs.add(errorLog);
            }
        }
    } 
    } else if(sobjectType == Log__c.getSObjectType()){
        errorLogs = (List<Log__c>)sObjectsList;
    }

    if(!errorLogs.isEmpty()){
        insert errorLogs;
    }

}

}