force-app/main/default/objects/Analitica__c/Analitica__c.object-meta.xml
<CustomObject>
    <label>Analítica</label>
    <nameField>
        <displayFormat>A-{YY}/{MM}-{0000}</displayFormat>
        <label>Nombre de Analítica</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analíticas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Analitica__c/fields/Importe__c.field-meta.xml
<CustomField>
    <fullName>Importe__c</fullName>
    <label>Importe Backlog</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <label>Mercado</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sectores</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Analitica__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Analíticas</relationshipLabel>
    <relationshipName>Analiticas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_Batch_Pipeline.cls
@isTest
public with sharing class Test_Batch_Pipeline {

     @isTest
    static void TestBatch()
    {
        List<Account> accs = TestUtil.generaCuentasTest();
        Id preventaRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(Constants.OPPORTUNITY_RECORDTYPE_PRESALE).getRecordTypeId();
        Opportunity opp1 = new Opportunity(
            Name = 'Opportunity 1',
            RecordTypeId = preventaRecordTypeId,
            StageName = Constants.OPPORTUNITY_STAGE_IDENTIFIED,
            CloseDate = Date.newInstance(2018, 12, 16),
            Mercado__c='Banca-Banca',
            Probability=50,
            Amount=99,
            AccountId=accs.get(0).id
        );

        insert(opp1);
        Test.startTest();
        Batch_Pipeline_Analitica batch = new Batch_Pipeline_Analitica(); 
        ID batchprocessid = Database.executeBatch(Batch); 

        Test.stopTest();
         Analitica__c analitica = [SELECT Id,importe__c FROM Analitica__c WHERE   Oportunidad__c =:opp1.id];
         system.assert(analitica.importe__c >0);
    }
}