force-app/main/default/objects/Usuario_de_Campana__c/Usuario_de_Campana__c.object-meta.xml
<CustomObject>
    <description>Objeto en el que se definen los usuarios objetivo de una campaña. Principalmente destinado a Account Managers</description>
    <label>Usuario de Campaña</label>
    <nameField>
        <displayFormat>CU-{00000}</displayFormat>
        <label>Número de Usuario de Campaña</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usuarios de Campaña</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Usuario_de_Campana__c/fields/Campana__c.field-meta.xml
<CustomField>
    <fullName>Campana__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaña</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Usuarios de Campaña</relationshipLabel>
    <relationshipName>Usuarios_de_Campana</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Usuario_de_Campana__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Usuarios_de_Campana_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CampaignUtil.cls
public class CampaignUtil 
{
	/**
	 * Recupera una lista de Usuario_de_Campana__c y un mapa con las campanas utilizadas en esa lista y
	 * devuelve un listado de tareas asociadas a los usuarios y campañas
	 * 
	 * @author: amartinez
	 **/
 /*   public static List<Task> createTaskToSalesReps(List<Usuario_de_Campana__c> usersAndCampaigns, Map<Id, Campaign> campaigns) 
    {
        List<Task> newTasks = new List<Task>();
         
        for (Usuario_de_Campana__c usu : usersAndCampaigns) 
        {
            Campaign camp = campaigns.get(usu.Campana__c);
            Task t = new Task();
            t.Subject = camp.Name;
            t.WhatId = camp.Id;
            t.Description = camp.Description;
            t.ActivityDate = camp.EndDate;
            t.OwnerId = usu.Usuario__c;
            newTasks.add(t);
        }
        
        return newTasks;
    }
    */

 
}