force-app/main/default/objects/E_Linea_de_Proyecto__e/E_Linea_de_Proyecto__e.object-meta.xml
<CustomObject>
    <description>Evento para integración con SAP, del sObject Linea_de_Proyecto__c</description>
    <label>Linea de Proyecto</label>
    <pluralLabel>Lineas de Proyecto</pluralLabel>
</CustomObject>

force-app/main/default/objects/E_Linea_de_Proyecto__e/fields/eOperacion__c.field-meta.xml
<CustomField>
    <fullName>eOperacion__c</fullName>
    <label>eOperacion</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/Linea_de_Proyecto__c.object-meta.xml
<CustomObject>
    <label>Línea de Proyecto</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Número de Línea de Proyecto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Proyecto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_MasEvents.cls
/**versión v1
*@description: Clase de test para MasEvents.
*@author name: rpolvera
*@date date: 12/11/2018
*@change name date description: Clase nueva.
*@see class/method: MasEvents
**/
@IsTest
private class Test_MasEvents {
    
    /**
    *@description: Prueba el flujo correcto del WS
    *@param name Description:
    *@author name: rpolvera
    *@date date: 12/10/2018
    *@change name date description: Nuevo Método.
    *@throws Exception: 
    *@where description: TEST.
    *@see class/method:
    **/    
    @isTest
    static void test_publicaEventosCorrecto()
    {
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri =
            '/services/apexrest/v1/sobjects/events';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('['
                                    +'{'
                                    +'"attributes": {'
                                    +'    "type": "E_Linea_de_Proyecto__e"'
                                    +'    },'
                                    +'"eOperacion__c":"update"'
                                    +'}'
                            +']');
        RestContext.request = request;
        RestContext.response = new RestResponse();
        // Call the method to test
        MasEvents.publicaEventos();
        system.assertEquals(RestContext.response.statusCode, 201);
    }
    
    /**
    *@description: Prueba el flujo con errores del servidor como un error de tipo de evento
                   o un error en campos obligatorios
    *@param name Description:
    *@author name: rpolvera
    *@date date: 12/10/2018
    *@change name date description: Nuevo Método.
    *@throws Exception: 
    *@where description: TEST.
    *@see class/method:
    **/    
    @isTest
    static void test_publicaEventosError()
    {
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri =
            '/services/apexrest/v1/sobjects/events';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('['
                                    +'{'
                                    +'"attributes": {'
                                    +'    "type": "Linea_de_Proyecto__c"'
                                    +'    },'
                                    +'"name":"prueba"'
                                    +'},'
                                    +'{'
                                    +'"attributes": {'
                                    +'    "type": "E_Linea_de_Proyecto__e"'
                                    +'    },'
                                    +'"eOperacion__c":""'
                                    +'}'
                            +']');
        RestContext.request = request;
        RestContext.response = new RestResponse();
        // Call the method to test
        MasEvents.publicaEventos();

        system.assertEquals(RestContext.response.statusCode, 500);
    }

    /**
    *@description: Prueba el flujo con errores del cliente como una mala estructura
                   en el JSON de entrada
    *@param name Description:
    *@author name: rpolvera
    *@date date: 12/10/2018
    *@change name date description: Nuevo Método.
    *@throws Exception: 
    *@where description: TEST.
    *@see class/method:
    **/  
    @isTest
    static void test_publicaEventosErrorJSON()
    {
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri =
            '/services/apexrest/v1/sobjects/events';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('['
                                    +'{'
                                    +'attributes": {'
                                    +'    "_de_Proyecto__e"'
                                    +'    },'
                                    +'"eOperacion__c":""'
                                    +'}'
                            +']');
        RestContext.request = request;
        RestContext.response = new RestResponse();
        // Call the method to test
        MasEvents.publicaEventos();

        system.assertEquals(RestContext.response.statusCode, 400);
    }    
}