force-app/main/default/objects/E_Linea_de_Proyecto__e/E_Linea_de_Proyecto__e.object-meta.xml
<CustomObject>
    <description>Evento para integración con SAP, del sObject Linea_de_Proyecto__c</description>
    <label>Linea de Proyecto</label>
    <pluralLabel>Lineas de Proyecto</pluralLabel>
</CustomObject>

force-app/main/default/objects/E_Linea_de_Proyecto__e/fields/Codigo_SAP_Ejecucion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP_Ejecucion__c</fullName>
    <label>Codigo SAP Ejecucion</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/E_Linea_de_Proyecto__e/fields/eOperacion__c.field-meta.xml
<CustomField>
    <fullName>eOperacion__c</fullName>
    <label>eOperacion</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_reprocesaEvento.cls
@Istest
private class Test_reprocesaEvento {
        
    /**
    *@description: Comprueba que se programa el Job que republica los eventos y
                   se aborta al terminar
    *@param name Description:
    *@author name: rpolvera
    *@date date: 12/10/2018
    *@change name date description: Nuevo Método.
    *@throws Exception: 
    *@where description: TEST.
    *@see class/method:
    **/  
    @isTest
    static void test_republicar()
    {
        List<E_Linea_de_Proyecto__e> eventoList = new List<E_Linea_de_Proyecto__e>();
        eventoList.add (
                        new E_Linea_de_Proyecto__e (
                        eoperacion__c ='UPDATE',
                        Codigo_SAP_Ejecucion__c = '11'
                        ) 
                        );
        ReprocesaEvento re = new ReprocesaEvento(eventoList);

        Integer hour = Datetime.now().hour();
        Integer min = Datetime.now().minute() + 30; 
        Integer ss = Datetime.now().second();
        
        if( min >= 60)
        {
            hour++;
            min = min - 60;
        }
        
        //parse to cron expression
        String nextFireTime = ss + ' ' + min + ' ' + hour + ' * * ?';
        //recuperamos el ID
        String jobId = System.schedule('Republicar Eventos ' + String.valueOf(Datetime.now()), nextFireTime, re);
        Test.startTest();
        //verificamos que existe el job
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
        //debería haber 1 job programado
        system.assertEquals(jobId, ct.ID);
        Test.stopTest();
        Integer jobs = [SELECT count() FROM CronTrigger WHERE id = :jobId]; 
        //el job debería haberse ejecutado y abortado
        system.assertEquals(jobs, 0);


    }   
}