force-app/main/default/objects/Hito_de_facturacion__c/Hito_de_facturacion__c.object-meta.xml
<CustomObject>
    <label>Hito de facturación</label>
    <nameField>
        <label>Nombre del hito de facturación</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hito de facturación</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hito_de_facturacion__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Hitos de facturación</relationshipLabel>
    <relationshipName>Hitos_de_facturacion</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/Linea_de_Proyecto__c.object-meta.xml
<CustomObject>
    <label>Línea de Proyecto</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Número de Línea de Proyecto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Líneas de Proyecto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Práctica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Gerencia__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Areas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Codigo_SAP_Ejecucion__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP_Ejecucion__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP Ejecución</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Codigo_SAP_Preventa__c.field-meta.xml
<CustomField>
    <fullName>Codigo_SAP_Preventa__c</fullName>
    <externalId>true</externalId>
    <label>Código SAP Preventa</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Coste_estimado__c.field-meta.xml
<CustomField>
    <fullName>Coste_estimado__c</fullName>
    <label>Coste estimado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/EsIntercompany__c.field-meta.xml
<CustomField>
    <fullName>EsIntercompany__c</fullName>
    <formula>if(
OR(TEXT(Sede__c)==&apos;1100&apos; &amp;&amp; TEXT(Oportunidad__r.Sede_Venta__r.Sede__c)==&apos;1000&apos;,
TEXT(Sede__c)==&apos;1000&apos; &amp;&amp; TEXT(Oportunidad__r.Sede_Venta__r.Sede__c)==&apos;1100&apos;,
TEXT(Sede__c)==&apos;1110&apos; &amp;&amp; TEXT(Oportunidad__r.Sede_Venta__r.Sede__c)==&apos;1120&apos;,
TEXT(Sede__c)==&apos;1120&apos; &amp;&amp; TEXT(Oportunidad__r.Sede_Venta__r.Sede__c)==&apos;1110&apos;,
TEXT(Oportunidad__r.Sede_Venta__r.Sede__c)==&apos;VASS Sweden&apos;,
TEXT(Oportunidad__r.Sede_Venta__r.Sede__c)==&apos;2110&apos;,
TEXT(Oportunidad__r.Sede_Venta__r.Sede__c)==&apos;2600&apos;,
TEXT(Oportunidad__r.Sede_Venta__r.Sede__c)==&apos;2700&apos;,
TEXT(Oportunidad__r.Sede_Venta__r.Sede__c)==&apos;6700&apos;,
TEXT(Oportunidad__r.Sede_Venta__r.Sede__c)==&apos;4710&apos;,
TEXT(Oportunidad__r.Sede_Venta__r.Sede__c)==&apos;6720&apos;


)


,false,  AND(TEXT(Sede__c)!= TEXT(Oportunidad__r.Sede_Venta__r.Sede__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EsIntercompany</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Execution_SAP_Name__c.field-meta.xml
<CustomField>
    <fullName>Execution_SAP_Name__c</fullName>
    <label>Execution SAP Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Fabricantes__c.field-meta.xml
<CustomField>
    <fullName>Fabricantes__c</fullName>
    <label>Fabricantes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fabricantes_de_Licencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Fecha_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Fin__c</fullName>
    <label>Fecha Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Gerencia__c.field-meta.xml
<CustomField>
    <fullName>Gerencia__c</fullName>
    <label>Área</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Gerencias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Importe_total_2__c.field-meta.xml
<CustomField>
    <fullName>Importe_total_2__c</fullName>
    <description>Nuevo campo para poder indicar de forma manual el importe final</description>
    <label>Importe total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Jefe_de_Proyecto_de_Ejecucion__c.field-meta.xml
<CustomField>
    <fullName>Jefe_de_Proyecto_de_Ejecucion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Jefe de Proyecto de Ejecución</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Jefe_de_Proyecto</value>
        </filterItems>
        <filterItems>
            <field>Contact.Activo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proyectos de Ejecución</relationshipLabel>
    <relationshipName>Lineas_de_JP_Ejecucion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Jefe_de_Proyecto_de_Preventa__c.field-meta.xml
<CustomField>
    <fullName>Jefe_de_Proyecto_de_Preventa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Operation user of the area involved</inlineHelpText>
    <label>Jefe de Proyecto de Preventa</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Jefe de Proyecto</value>
        </filterItems>
        <filterItems>
            <field>Contact.Activo__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proyectos de Preventa</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Jefe_Proyecto_Ejecucion_Adicional__c.field-meta.xml
<CustomField>
    <fullName>Jefe_Proyecto_Ejecucion_Adicional__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Jefe Proyecto Ejecución Adicional</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Id</field>
            <operation>equals</operation>
            <value>0120N000000UzjjQAC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Líneas de Proyecto (Jefe Proyecto Ejecución Adicional)</relationshipLabel>
    <relationshipName>L_neas_de_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Linea_principal__c.field-meta.xml
<CustomField>
    <fullName>Linea_principal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si se trata o no del proyecto principal dentro de la oportunidad. Usado posteriormente para generar los PEPs en SAP.</description>
    <inlineHelpText>Shows if its the main opportunity proyect. Used after to generate PEP in SAP:</inlineHelpText>
    <label>Línea principal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Margen_bruto__c.field-meta.xml
<CustomField>
    <fullName>Margen_bruto__c</fullName>
    <label>Margen bruto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Margen_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Margen_de_venta__c</fullName>
    <description>Cálculo del margen en base al precio y al coste</description>
    <formula>if( Importe_de_licencias__c &gt;0,Margen_de_licencias__c,((Importe_total_2__c - Coste_estimado__c) / Importe_total_2__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margen de venta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Margen_real__c.field-meta.xml
<CustomField>
    <fullName>Margen_real__c</fullName>
    <label>Margen real</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Mercado__c.field-meta.xml
<CustomField>
    <fullName>Mercado__c</fullName>
    <formula>Text( Oportunidad__r.Mercado__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mercado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/NEW_Nombre_SAP__c.field-meta.xml
<CustomField>
    <fullName>NEW_Nombre_SAP__c</fullName>
    <label>Nombre SAP</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/No_aplica_para_ejecucion__c.field-meta.xml
<CustomField>
    <fullName>No_aplica_para_ejecucion__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If this project line does not count towards the pipeline, it will not be synchronized with SAP</inlineHelpText>
    <label>No aplica para ejecución</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oficina_tecnica__c.field-meta.xml
<CustomField>
    <fullName>Oficina_tecnica__c</fullName>
    <inlineHelpText>Technical office where the project line will be executed</inlineHelpText>
    <label>Oficina técnica</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Oficina_t_cnica</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Líneas de Proyecto</relationshipLabel>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Org_Ventas__c.field-meta.xml
<CustomField>
    <fullName>Org_Ventas__c</fullName>
    <label>Org Ventas (Delivery Company)</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sede__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Org_Ventas</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/PEP_Interco__c.field-meta.xml
<CustomField>
    <fullName>PEP_Interco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Interco PEP project line has to be sync with SAP</inlineHelpText>
    <label>PEP Interco</label>
    <referenceTo>Linea_de_Proyecto__c</referenceTo>
    <relationshipLabel>Project Lines</relationshipLabel>
    <relationshipName>Project_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Precio_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_Venta__c</fullName>
    <label>Precio Venta</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Responsable_de_LDP__c.field-meta.xml
<CustomField>
    <fullName>Responsable_de_LDP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>antiguamente era el campo Responsable_de_la_oferta__c</description>
    <inlineHelpText>Operation user of the area involved</inlineHelpText>
    <label>Responsable de oferta(Operaciones)</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>El responsable de la oferta tiene que estar dada de alta como gerente en SAP.</errorMessage>
        <filterItems>
            <field>User.Gerente__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Lineas_de_Proyecto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Sede__c.field-meta.xml
<CustomField>
    <fullName>Sede__c</fullName>
    <defaultValue>if( ISPICKVAL($User.Sede__c ,&apos;1210&apos;),&apos;1210&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1110&apos;),&apos;1110&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Perú&apos;),&apos;VASS Perú&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Colombia&apos;),&apos;VASS Colombia&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS México&apos;),&apos;VASS México&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Chile&apos;),&apos;VASS Chile&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS UK&apos;),&apos;VASS UK&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;VASS Benelux&apos;),&apos;VASS Benelux&apos;,
if(ISPICKVAL($User.Sede__c ,&apos;1800&apos;),&apos;1800&apos;,&apos;1000&apos;

)))))))))</defaultValue>
    <label>Sede (Delivery Company)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sede</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Strategic_Partner__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Partner__c</fullName>
    <label>Strategic Partner</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Strategic_Partner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/fields/Tecnologia__c.field-meta.xml
<CustomField>
    <fullName>Tecnologia__c</fullName>
    <label>Competencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tecnologias</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Linea_de_Proyecto__c/recordTypes/Licencias.recordType-meta.xml
<RecordType>
    <fullName>Licencias</fullName>
    <active>true</active>
    <label>Licencias</label>
</RecordType>

force-app/main/default/classes/EPPM_Selector.cls
public inherited sharing class EPPM_Selector {
    public static List<Opportunity> getOpportunitiesWithDetails(Set<Id> opportunityIds) {
        return [SELECT 
            Id, Codigo_de_oportunidad__c, RecordType.Name, 
            N_Cargas_Excel__c, Oportunidad_Relacionada__r.Codigo_de_oportunidad__c, 
            Name, Fecha_de_inicio__c, Fecha_de_fin__c, CreatedDate, CloseDate,
            Sede_Venta__r.sede__c, CurrencyIsoCode,HasLineInterco__c, LOB__c, Description, Clan_Principal__c,
            Margen_real__c, Amount, Strategic_Partner__c, Account.ID_SAP__c,StageName, Account.Name,GPM__r.Codigo_de_empleado__c,Margen_bruto__c,
            Owner.EmployeeNumber, Probability, Commited__c, ID_SAP__c, EPPMID__c , GSO_Validated__c,Bid_Manager__r.employeenumber,GSO_Sede__c,
            Framework_Contract__r.Codigo_de_oportunidad__c, Mercado__c,type,
            (SELECT 
                Id, Fecha_Inicio__c, Fecha_Fin__c, Oportunidad__r.Codigo_de_oportunidad__c,
                Sede__c, Org_Ventas__c, Name, Oficina_tecnica__c, RecordType.Name,Coste_estimado__c,
                Gerencia__c, Area__c, Linea_principal__c, Importe_total_2__c, No_aplica_para_ejecucion__c,
                Margen_de_venta__c, Precio_Venta__c, CurrencyIsoCode, Fabricantes__c,
                Responsable_de_LDP__r.EmployeeNumber, Jefe_de_Proyecto_de_Preventa__r.Codigo_de_empleado__c,Margen_bruto__c,
                Jefe_de_Proyecto_de_Ejecucion__r.Codigo_de_empleado__c, Oportunidad__r.Account.Name,Oportunidad__r.Account.ID_SAP__c,Oportunidad__r.GPM__r.Codigo_de_empleado__c,
                Jefe_Proyecto_Ejecucion_Adicional__r.Codigo_de_empleado__c, PEP_Interco__r.Name,Tecnologia__c,Oportunidad__r.StageName,
              	Oportunidad__r.Owner.EmployeeNumber,Oportunidad__r.Bid_Manager__r.employeenumber,NEW_Nombre_SAP__c,Execution_SAP_Name__c,
                LOB__c, Oportunidad__r.Proyecto_Padre__c, Oportunidad__r.Mercado__c,EsIntercompany__c,Oportunidad__r.CreatedDate,Codigo_SAP_Ejecucion__c,Codigo_SAP_Preventa__c
             FROM Lineas_de_proyecto__r where   Agrupacion_Tipo_Registro__c!='Licencias')
        FROM Opportunity 
        WHERE Id IN :opportunityIds   ];
    }

    public static Map<Id, List<Hito_de_facturacion__c>> getHitosPorLinea(Set<Id> opportunityIds) {
        Map<Id, List<Hito_de_facturacion__c>> hitosPorLinea = new Map<Id, List<Hito_de_facturacion__c>>();
        
        for (Hito_de_facturacion__c hito : [
            SELECT 
                Fecha__c, Name, Id, Descripcion__c, oportunidad__r.Codigo_de_oportunidad__c,
                Importe__c, Porcentaje__c, Linea_de_Proyecto__c ,OppCode__c
            FROM Hito_de_facturacion__c 
            WHERE Linea_de_Proyecto__r.Oportunidad__c IN :opportunityIds
        ]) {
            if (!hitosPorLinea.containsKey(hito.Linea_de_Proyecto__c)) {
                hitosPorLinea.put(hito.Linea_de_Proyecto__c, new List<Hito_de_facturacion__c>());
            }
            hitosPorLinea.get(hito.Linea_de_Proyecto__c).add(hito);
        }
        
        return hitosPorLinea;
    }
}